package dgcom.model.vo.inv;

import java.math.BigInteger;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 15 11:21:27 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemImeiInfoVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ItemImeiInfoVOImpl() {
    }

    /**
     * Returns the variable value for P_ADF_IMEI_NO.
     * @return variable value for P_ADF_IMEI_NO
     */
    public BigInteger getP_ADF_IMEI_NO() {
        return (BigInteger) ensureVariableManager().getVariableValue("P_ADF_IMEI_NO");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_IMEI_NO.
     * @param value value to bind as P_ADF_IMEI_NO
     */
    public void setP_ADF_IMEI_NO(BigInteger value) {
        ensureVariableManager().setVariableValue("P_ADF_IMEI_NO", value);
    }

    /**
     * Returns the variable value for P_ADF_ITEMID.
     * @return variable value for P_ADF_ITEMID
     */
    public String getP_ADF_ITEMID() {
        return (String) ensureVariableManager().getVariableValue("P_ADF_ITEMID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_ITEMID.
     * @param value value to bind as P_ADF_ITEMID
     */
    public void setP_ADF_ITEMID(String value) {
        ensureVariableManager().setVariableValue("P_ADF_ITEMID", value);
    }

    /**
     * Returns the variable value for P_ADF_STOREID.
     * @return variable value for P_ADF_STOREID
     */
    public String getP_ADF_STOREID() {
        return (String) ensureVariableManager().getVariableValue("P_ADF_STOREID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_STOREID.
     * @param value value to bind as P_ADF_STOREID
     */
    public void setP_ADF_STOREID(String value) {
        ensureVariableManager().setVariableValue("P_ADF_STOREID", value);
    }
}

