package dgcom.model.vo.inv;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 11 12:10:17 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SoProductBrandsVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SoProductBrandsVOImpl() {
    }
}

