package dgcom.model.eo.srv;

import dgcom.model.eo.inv.InItemsImpl;
import dgcom.model.stand.DigicomEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 03 16:29:34 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AllDemandLinesImpl extends DigicomEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Dmditemid,
        DemandId,
        Itemid,
        OrderQty,
        GrinQty,
        IssuedQty,
        CancelQty,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Partid,
        DemandQty,
        UsedQty,
        txtPartNo,
        txtPartName,
        txtModelNo,
        AllDemandNote,
        InParts,
        InItems,
        SrvStnparts,
        AccSrvAllDemandLinesDemandQuantityChecking;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DMDITEMID = AttributesEnum.Dmditemid.index();
    public static final int DEMANDID = AttributesEnum.DemandId.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int GRINQTY = AttributesEnum.GrinQty.index();
    public static final int ISSUEDQTY = AttributesEnum.IssuedQty.index();
    public static final int CANCELQTY = AttributesEnum.CancelQty.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int PARTID = AttributesEnum.Partid.index();
    public static final int DEMANDQTY = AttributesEnum.DemandQty.index();
    public static final int USEDQTY = AttributesEnum.UsedQty.index();
    public static final int TXTPARTNO = AttributesEnum.txtPartNo.index();
    public static final int TXTPARTNAME = AttributesEnum.txtPartName.index();
    public static final int TXTMODELNO = AttributesEnum.txtModelNo.index();
    public static final int ALLDEMANDNOTE = AttributesEnum.AllDemandNote.index();
    public static final int INPARTS = AttributesEnum.InParts.index();
    public static final int INITEMS = AttributesEnum.InItems.index();
    public static final int SRVSTNPARTS = AttributesEnum.SrvStnparts.index();
    public static final int ACCSRVALLDEMANDLINESDEMANDQUANTITYCHECKING =
        AttributesEnum.AccSrvAllDemandLinesDemandQuantityChecking.index();

    /**
     * This is the default constructor (do not remove).
     */
    public AllDemandLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("dgcom.model.eo.srv.AllDemandLines");
    }


    /**
     * Gets the attribute value for Dmditemid, using the alias name Dmditemid.
     * @return the value of Dmditemid
     */
    public String getDmditemid() {
        return (String) getAttributeInternal(DMDITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dmditemid.
     * @param value value to set the Dmditemid
     */
    public void setDmditemid(String value) {
        setAttributeInternal(DMDITEMID, value);
    }

    /**
     * Gets the attribute value for DemandId, using the alias name DemandId.
     * @return the value of DemandId
     */
    public String getDemandId() {
        return (String) getAttributeInternal(DEMANDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DemandId.
     * @param value value to set the DemandId
     */
    public void setDemandId(String value) {
        setAttributeInternal(DEMANDID, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for OrderQty, using the alias name OrderQty.
     * @return the value of OrderQty
     */
    public BigDecimal getOrderQty() {
        return (BigDecimal) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQty.
     * @param value value to set the OrderQty
     */
    public void setOrderQty(BigDecimal value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for GrinQty, using the alias name GrinQty.
     * @return the value of GrinQty
     */
    public BigDecimal getGrinQty() {
        return (BigDecimal) getAttributeInternal(GRINQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrinQty.
     * @param value value to set the GrinQty
     */
    public void setGrinQty(BigDecimal value) {
        setAttributeInternal(GRINQTY, value);
    }

    /**
     * Gets the attribute value for IssuedQty, using the alias name IssuedQty.
     * @return the value of IssuedQty
     */
    public BigDecimal getIssuedQty() {
        return (BigDecimal) getAttributeInternal(ISSUEDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for IssuedQty.
     * @param value value to set the IssuedQty
     */
    public void setIssuedQty(BigDecimal value) {
        setAttributeInternal(ISSUEDQTY, value);
    }

    /**
     * Gets the attribute value for CancelQty, using the alias name CancelQty.
     * @return the value of CancelQty
     */
    public BigDecimal getCancelQty() {
        return (BigDecimal) getAttributeInternal(CANCELQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CancelQty.
     * @param value value to set the CancelQty
     */
    public void setCancelQty(BigDecimal value) {
        setAttributeInternal(CANCELQTY, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Partid, using the alias name Partid.
     * @return the value of Partid
     */
    public String getPartid() {
        return (String) getAttributeInternal(PARTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Partid.
     * @param value value to set the Partid
     */
    public void setPartid(String value) {
        setAttributeInternal(PARTID, value);
    }

    /**
     * Gets the attribute value for DemandQty, using the alias name DemandQty.
     * @return the value of DemandQty
     */
    public BigDecimal getDemandQty() {
        return (BigDecimal) getAttributeInternal(DEMANDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DemandQty.
     * @param value value to set the DemandQty
     */
    public void setDemandQty(BigDecimal value) {
        setAttributeInternal(DEMANDQTY, value);
    }

    /**
     * Gets the attribute value for UsedQty, using the alias name UsedQty.
     * @return the value of UsedQty
     */
    public BigDecimal getUsedQty() {
        return (BigDecimal) getAttributeInternal(USEDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UsedQty.
     * @param value value to set the UsedQty
     */
    public void setUsedQty(BigDecimal value) {
        setAttributeInternal(USEDQTY, value);
    }

    /**
     * Gets the attribute value for txtPartNo, using the alias name txtPartNo.
     * @return the value of txtPartNo
     */
    public String gettxtPartNo() {
        return (String) getAttributeInternal(TXTPARTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtPartNo.
     * @param value value to set the txtPartNo
     */
    public void settxtPartNo(String value) {
        setAttributeInternal(TXTPARTNO, value);
    }

    /**
     * Gets the attribute value for txtPartName, using the alias name txtPartName.
     * @return the value of txtPartName
     */
    public String gettxtPartName() {
        return (String) getAttributeInternal(TXTPARTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtPartName.
     * @param value value to set the txtPartName
     */
    public void settxtPartName(String value) {
        setAttributeInternal(TXTPARTNAME, value);
    }

    /**
     * Gets the attribute value for txtModelNo, using the alias name txtModelNo.
     * @return the value of txtModelNo
     */
    public String gettxtModelNo() {
        return (String) getAttributeInternal(TXTMODELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtModelNo.
     * @param value value to set the txtModelNo
     */
    public void settxtModelNo(String value) {
        setAttributeInternal(TXTMODELNO, value);
    }

    /**
     * @return the associated entity AllDemandNoteImpl.
     */
    public AllDemandNoteImpl getAllDemandNote() {
        return (AllDemandNoteImpl) getAttributeInternal(ALLDEMANDNOTE);
    }

    /**
     * Sets <code>value</code> as the associated entity AllDemandNoteImpl.
     */
    public void setAllDemandNote(AllDemandNoteImpl value) {
        setAttributeInternal(ALLDEMANDNOTE, value);
    }

    /**
     * @return the associated entity InPartsImpl.
     */
    public InPartsImpl getInParts() {
        return (InPartsImpl) getAttributeInternal(INPARTS);
    }

    /**
     * Sets <code>value</code> as the associated entity InPartsImpl.
     */
    public void setInParts(InPartsImpl value) {
        setAttributeInternal(INPARTS, value);
    }

    /**
     * @return the associated entity dgcom.model.eo.inv.InItemsImpl.
     */
    public InItemsImpl getInItems() {
        return (InItemsImpl) getAttributeInternal(INITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity dgcom.model.eo.inv.InItemsImpl.
     */
    public void setInItems(InItemsImpl value) {
        setAttributeInternal(INITEMS, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSrvStnparts() {
        return (RowIterator) getAttributeInternal(SRVSTNPARTS);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvAllDemandLinesDemandQuantityChecking.
     */
    public RowSet getAccSrvAllDemandLinesDemandQuantityChecking() {
        return (RowSet) getAttributeInternal(ACCSRVALLDEMANDLINESDEMANDQUANTITYCHECKING);
    }


    /**
     * @param dmditemid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String dmditemid) {
        return new Key(new Object[] { dmditemid });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT && getPartid()==null) {
            remove();
            return;
       }
        if (operation==DML_INSERT) {
            ApplicationModule am=this.getDBTransaction().getRootApplicationModule();
            ViewObject        vo=am.findViewObject("myAllDemandNoteLinePK");
            if (vo!=null)
                {
                   vo.remove();     
                }
            vo=am.createViewObjectFromQueryStmt("myAllDemandNoteLinePK",
                                                "Select '"+getAllDemandNote().getAttribute("DemandId").toString()+"-'||nvl(max(to_number(substr(DMDITEMID,length(DEMAND_ID)+2)))+1,1) "+
                                                "from ALL_DEMAND_LINES \n"+
                                                "Where DEMAND_ID='"+ getAllDemandNote().getAttribute("DemandId").toString()+"'");
            vo.executeQuery();
            setDmditemid(vo.first().getAttribute(0).toString());
        }  
        super.doDML(operation, e);
        }
}

