package dgcom.model.eo.srv;

import dgcom.model.eo.inv.InItemsImpl;
import dgcom.model.stand.DigicomEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Key;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 04 22:40:26 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PuPoLinesImpl extends DigicomEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Poitemid,
        Poid,
        Dmditemid,
        Itemid,
        ItemType,
        DemandQty,
        OrderQty,
        ConfirmedQty,
        CancelQty,
        DeliveryDate,
        UnitPriceInFcurr,
        UnitPriceInBcurr,
        Hscode,
        HsRate,
        Remarks,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Polineno,
        Partid,
        GrnQty,
        LcNo,
        GdNo,
        AirwaysBillno,
        GrnNo,
        FocQty,
        ExtraQty,
        txtDemand,
        txtPartNo,
        txtPartName,
        txtModelNo,
        txtUnitPriceInBcurr,
        PuPurchaseOrders,
        InParts,
        InItems;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int POITEMID = AttributesEnum.Poitemid.index();
    public static final int POID = AttributesEnum.Poid.index();
    public static final int DMDITEMID = AttributesEnum.Dmditemid.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ITEMTYPE = AttributesEnum.ItemType.index();
    public static final int DEMANDQTY = AttributesEnum.DemandQty.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int CONFIRMEDQTY = AttributesEnum.ConfirmedQty.index();
    public static final int CANCELQTY = AttributesEnum.CancelQty.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int UNITPRICEINFCURR = AttributesEnum.UnitPriceInFcurr.index();
    public static final int UNITPRICEINBCURR = AttributesEnum.UnitPriceInBcurr.index();
    public static final int HSCODE = AttributesEnum.Hscode.index();
    public static final int HSRATE = AttributesEnum.HsRate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int POLINENO = AttributesEnum.Polineno.index();
    public static final int PARTID = AttributesEnum.Partid.index();
    public static final int GRNQTY = AttributesEnum.GrnQty.index();
    public static final int LCNO = AttributesEnum.LcNo.index();
    public static final int GDNO = AttributesEnum.GdNo.index();
    public static final int AIRWAYSBILLNO = AttributesEnum.AirwaysBillno.index();
    public static final int GRNNO = AttributesEnum.GrnNo.index();
    public static final int FOCQTY = AttributesEnum.FocQty.index();
    public static final int EXTRAQTY = AttributesEnum.ExtraQty.index();
    public static final int TXTDEMAND = AttributesEnum.txtDemand.index();
    public static final int TXTPARTNO = AttributesEnum.txtPartNo.index();
    public static final int TXTPARTNAME = AttributesEnum.txtPartName.index();
    public static final int TXTMODELNO = AttributesEnum.txtModelNo.index();
    public static final int TXTUNITPRICEINBCURR = AttributesEnum.txtUnitPriceInBcurr.index();
    public static final int PUPURCHASEORDERS = AttributesEnum.PuPurchaseOrders.index();
    public static final int INPARTS = AttributesEnum.InParts.index();
    public static final int INITEMS = AttributesEnum.InItems.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PuPoLinesImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("dgcom.model.eo.srv.PuPoLines");
    }


    /**
     * Gets the attribute value for Poitemid, using the alias name Poitemid.
     * @return the value of Poitemid
     */
    public String getPoitemid() {
        return (String) getAttributeInternal(POITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Poitemid.
     * @param value value to set the Poitemid
     */
    public void setPoitemid(String value) {
        setAttributeInternal(POITEMID, value);
    }

    /**
     * Gets the attribute value for Poid, using the alias name Poid.
     * @return the value of Poid
     */
    public String getPoid() {
        return (String) getAttributeInternal(POID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Poid.
     * @param value value to set the Poid
     */
    public void setPoid(String value) {
        setAttributeInternal(POID, value);
    }

    /**
     * Gets the attribute value for Dmditemid, using the alias name Dmditemid.
     * @return the value of Dmditemid
     */
    public String getDmditemid() {
        return (String) getAttributeInternal(DMDITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Dmditemid.
     * @param value value to set the Dmditemid
     */
    public void setDmditemid(String value) {
        setAttributeInternal(DMDITEMID, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ItemType, using the alias name ItemType.
     * @return the value of ItemType
     */
    public String getItemType() {
        return (String) getAttributeInternal(ITEMTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemType.
     * @param value value to set the ItemType
     */
    public void setItemType(String value) {
        setAttributeInternal(ITEMTYPE, value);
    }

    /**
     * Gets the attribute value for DemandQty, using the alias name DemandQty.
     * @return the value of DemandQty
     */
    public BigDecimal getDemandQty() {
        return (BigDecimal) getAttributeInternal(DEMANDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for DemandQty.
     * @param value value to set the DemandQty
     */
    public void setDemandQty(BigDecimal value) {
        setAttributeInternal(DEMANDQTY, value);
    }

    /**
     * Gets the attribute value for OrderQty, using the alias name OrderQty.
     * @return the value of OrderQty
     */
    public BigDecimal getOrderQty() {
        return (BigDecimal) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrderQty.
     * @param value value to set the OrderQty
     */
    public void setOrderQty(BigDecimal value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for ConfirmedQty, using the alias name ConfirmedQty.
     * @return the value of ConfirmedQty
     */
    public BigDecimal getConfirmedQty() {
        return (BigDecimal) getAttributeInternal(CONFIRMEDQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ConfirmedQty.
     * @param value value to set the ConfirmedQty
     */
    public void setConfirmedQty(BigDecimal value) {
        setAttributeInternal(CONFIRMEDQTY, value);
    }

    /**
     * Gets the attribute value for CancelQty, using the alias name CancelQty.
     * @return the value of CancelQty
     */
    public BigDecimal getCancelQty() {
        return (BigDecimal) getAttributeInternal(CANCELQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CancelQty.
     * @param value value to set the CancelQty
     */
    public void setCancelQty(BigDecimal value) {
        setAttributeInternal(CANCELQTY, value);
    }

    /**
     * Gets the attribute value for DeliveryDate, using the alias name DeliveryDate.
     * @return the value of DeliveryDate
     */
    public Date getDeliveryDate() {
        return (Date) getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate.
     * @param value value to set the DeliveryDate
     */
    public void setDeliveryDate(Date value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for UnitPriceInFcurr, using the alias name UnitPriceInFcurr.
     * @return the value of UnitPriceInFcurr
     */
    public BigDecimal getUnitPriceInFcurr() {
        return (BigDecimal) getAttributeInternal(UNITPRICEINFCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitPriceInFcurr.
     * @param value value to set the UnitPriceInFcurr
     */
    public void setUnitPriceInFcurr(BigDecimal value) {
        setAttributeInternal(UNITPRICEINFCURR, value);
    }

    /**
     * Gets the attribute value for UnitPriceInBcurr, using the alias name UnitPriceInBcurr.
     * @return the value of UnitPriceInBcurr
     */
    public BigDecimal getUnitPriceInBcurr() {
        return (BigDecimal) getAttributeInternal(UNITPRICEINBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitPriceInBcurr.
     * @param value value to set the UnitPriceInBcurr
     */
    public void setUnitPriceInBcurr(BigDecimal value) {
        setAttributeInternal(UNITPRICEINBCURR, value);
    }

    /**
     * Gets the attribute value for Hscode, using the alias name Hscode.
     * @return the value of Hscode
     */
    public String getHscode() {
        return (String) getAttributeInternal(HSCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Hscode.
     * @param value value to set the Hscode
     */
    public void setHscode(String value) {
        setAttributeInternal(HSCODE, value);
    }

    /**
     * Gets the attribute value for HsRate, using the alias name HsRate.
     * @return the value of HsRate
     */
    public BigDecimal getHsRate() {
        return (BigDecimal) getAttributeInternal(HSRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HsRate.
     * @param value value to set the HsRate
     */
    public void setHsRate(BigDecimal value) {
        setAttributeInternal(HSRATE, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Polineno, using the alias name Polineno.
     * @return the value of Polineno
     */
    public BigDecimal getPolineno() {
        return (BigDecimal) getAttributeInternal(POLINENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Polineno.
     * @param value value to set the Polineno
     */
    public void setPolineno(BigDecimal value) {
        setAttributeInternal(POLINENO, value);
    }

    /**
     * Gets the attribute value for Partid, using the alias name Partid.
     * @return the value of Partid
     */
    public String getPartid() {
        return (String) getAttributeInternal(PARTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Partid.
     * @param value value to set the Partid
     */
    public void setPartid(String value) {
        setAttributeInternal(PARTID, value);
    }

    /**
     * Gets the attribute value for GrnQty, using the alias name GrnQty.
     * @return the value of GrnQty
     */
    public BigDecimal getGrnQty() {
        return (BigDecimal) getAttributeInternal(GRNQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrnQty.
     * @param value value to set the GrnQty
     */
    public void setGrnQty(BigDecimal value) {
        setAttributeInternal(GRNQTY, value);
    }

    /**
     * Gets the attribute value for LcNo, using the alias name LcNo.
     * @return the value of LcNo
     */
    public String getLcNo() {
        return (String) getAttributeInternal(LCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for LcNo.
     * @param value value to set the LcNo
     */
    public void setLcNo(String value) {
        setAttributeInternal(LCNO, value);
    }

    /**
     * Gets the attribute value for GdNo, using the alias name GdNo.
     * @return the value of GdNo
     */
    public String getGdNo() {
        return (String) getAttributeInternal(GDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GdNo.
     * @param value value to set the GdNo
     */
    public void setGdNo(String value) {
        setAttributeInternal(GDNO, value);
    }

    /**
     * Gets the attribute value for AirwaysBillno, using the alias name AirwaysBillno.
     * @return the value of AirwaysBillno
     */
    public String getAirwaysBillno() {
        return (String) getAttributeInternal(AIRWAYSBILLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for AirwaysBillno.
     * @param value value to set the AirwaysBillno
     */
    public void setAirwaysBillno(String value) {
        setAttributeInternal(AIRWAYSBILLNO, value);
    }

    /**
     * Gets the attribute value for GrnNo, using the alias name GrnNo.
     * @return the value of GrnNo
     */
    public String getGrnNo() {
        return (String) getAttributeInternal(GRNNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for GrnNo.
     * @param value value to set the GrnNo
     */
    public void setGrnNo(String value) {
        setAttributeInternal(GRNNO, value);
    }

    /**
     * Gets the attribute value for FocQty, using the alias name FocQty.
     * @return the value of FocQty
     */
    public BigDecimal getFocQty() {
        return (BigDecimal) getAttributeInternal(FOCQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for FocQty.
     * @param value value to set the FocQty
     */
    public void setFocQty(BigDecimal value) {
        setAttributeInternal(FOCQTY, value);
    }

    /**
     * Gets the attribute value for ExtraQty, using the alias name ExtraQty.
     * @return the value of ExtraQty
     */
    public BigDecimal getExtraQty() {
        return (BigDecimal) getAttributeInternal(EXTRAQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExtraQty.
     * @param value value to set the ExtraQty
     */
    public void setExtraQty(BigDecimal value) {
        setAttributeInternal(EXTRAQTY, value);
    }

    /**
     * Gets the attribute value for txtDemand, using the alias name txtDemand.
     * @return the value of txtDemand
     */
    public String gettxtDemand() {
        return (String) getAttributeInternal(TXTDEMAND);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtDemand.
     * @param value value to set the txtDemand
     */
    public void settxtDemand(String value) {
        setAttributeInternal(TXTDEMAND, value);
    }

    /**
     * Gets the attribute value for txtPartNo, using the alias name txtPartNo.
     * @return the value of txtPartNo
     */
    public String gettxtPartNo() {
        return (String) getAttributeInternal(TXTPARTNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtPartNo.
     * @param value value to set the txtPartNo
     */
    public void settxtPartNo(String value) {
        setAttributeInternal(TXTPARTNO, value);
    }

    /**
     * Gets the attribute value for txtPartName, using the alias name txtPartName.
     * @return the value of txtPartName
     */
    public String gettxtPartName() {
        return (String) getAttributeInternal(TXTPARTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtPartName.
     * @param value value to set the txtPartName
     */
    public void settxtPartName(String value) {
        setAttributeInternal(TXTPARTNAME, value);
    }

    /**
     * Gets the attribute value for txtModelNo, using the alias name txtModelNo.
     * @return the value of txtModelNo
     */
    public String gettxtModelNo() {
        return (String) getAttributeInternal(TXTMODELNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtModelNo.
     * @param value value to set the txtModelNo
     */
    public void settxtModelNo(String value) {
        setAttributeInternal(TXTMODELNO, value);
    }

    /**
     * Gets the attribute value for txtUnitPriceInBcurr, using the alias name txtUnitPriceInBcurr.
     * @return the value of txtUnitPriceInBcurr
     */
    public BigDecimal gettxtUnitPriceInBcurr() {
        return (BigDecimal) getAttributeInternal(TXTUNITPRICEINBCURR);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtUnitPriceInBcurr.
     * @param value value to set the txtUnitPriceInBcurr
     */
    public void settxtUnitPriceInBcurr(BigDecimal value) {
        setAttributeInternal(TXTUNITPRICEINBCURR, value);
    }

    /**
     * @return the associated entity PuPurchaseOrdersImpl.
     */
    public PuPurchaseOrdersImpl getPuPurchaseOrders() {
        return (PuPurchaseOrdersImpl) getAttributeInternal(PUPURCHASEORDERS);
    }

    /**
     * Sets <code>value</code> as the associated entity PuPurchaseOrdersImpl.
     */
    public void setPuPurchaseOrders(PuPurchaseOrdersImpl value) {
        setAttributeInternal(PUPURCHASEORDERS, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public InPartsImpl getInParts() {
        return (InPartsImpl) getAttributeInternal(INPARTS);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setInParts(InPartsImpl value) {
        setAttributeInternal(INPARTS, value);
    }


    /**
     * @return the associated entity dgcom.model.eo.inv.InItemsImpl.
     */
    public InItemsImpl getInItems() {
        return (InItemsImpl) getAttributeInternal(INITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity dgcom.model.eo.inv.InItemsImpl.
     */
    public void setInItems(InItemsImpl value) {
        setAttributeInternal(INITEMS, value);
    }


    /**
     * @param poitemid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String poitemid) {
        return new Key(new Object[] { poitemid });
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT && getPartid()==null) {
            remove();
            return;
       }
        if (operation==DML_INSERT) {
            ApplicationModule am=this.getDBTransaction().getRootApplicationModule();
            ViewObject        vo=am.findViewObject("myPuPoLinesPk");
            if (vo!=null)
                {
                   vo.remove();     
                }
            vo=am.createViewObjectFromQueryStmt("myPuPoLinesPk",
                                                "Select '"+getPuPurchaseOrders().getAttribute("Poid").toString()+"-'||nvl(max(to_number(substr(POItemId,length(POId)+2)))+1,1) "+
                                                "from PU_PO_LINES \n"+
                                                "Where Poid='"+ getPuPurchaseOrders().getAttribute("Poid").toString()+"'");
            vo.executeQuery();
            setPoitemid(vo.first().getAttribute(0).toString());
        } 
        if (operation!=DML_DELETE) {
           setUnitPriceInBcurr(gettxtUnitPriceInBcurr());
       }
        super.doDML(operation, e);
        }
}

