package dgcom.model.eo.srv;

import dgcom.model.stand.DigicomClass;
import dgcom.model.stand.DigicomEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 05 14:05:47 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvInvoiceImpl extends DigicomEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SrvInvno,
        Locationid,
        Jobcardno,
        Reasonid,
        InvDate,
        Charges,
        Discount,
        Received,
        Rcptmode,
        Referno,
        Remarks,
        Posted,
        Postedby,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        RecAmnt,
        ReceAmnt,
        InvAmnt,
        DocTypeId,
        PrevDoctype,
        PrevDocid,
        ReceDisc,
        ChrgesDiscount,
        PartDiscount,
        Chk,
        ReplaceAmount,
        IsMigrated,
        MigratedDate,
        txtSumPartCost,
        txtDiscount,
        txtReceived,
        txtTotal,
        SrvInvItems,
        SrvJobcard,
        AccSrvInvoiceItemSrvPartDetail;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SRVINVNO = AttributesEnum.SrvInvno.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int JOBCARDNO = AttributesEnum.Jobcardno.index();
    public static final int REASONID = AttributesEnum.Reasonid.index();
    public static final int INVDATE = AttributesEnum.InvDate.index();
    public static final int CHARGES = AttributesEnum.Charges.index();
    public static final int DISCOUNT = AttributesEnum.Discount.index();
    public static final int RECEIVED = AttributesEnum.Received.index();
    public static final int RCPTMODE = AttributesEnum.Rcptmode.index();
    public static final int REFERNO = AttributesEnum.Referno.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int RECAMNT = AttributesEnum.RecAmnt.index();
    public static final int RECEAMNT = AttributesEnum.ReceAmnt.index();
    public static final int INVAMNT = AttributesEnum.InvAmnt.index();
    public static final int DOCTYPEID = AttributesEnum.DocTypeId.index();
    public static final int PREVDOCTYPE = AttributesEnum.PrevDoctype.index();
    public static final int PREVDOCID = AttributesEnum.PrevDocid.index();
    public static final int RECEDISC = AttributesEnum.ReceDisc.index();
    public static final int CHRGESDISCOUNT = AttributesEnum.ChrgesDiscount.index();
    public static final int PARTDISCOUNT = AttributesEnum.PartDiscount.index();
    public static final int CHK = AttributesEnum.Chk.index();
    public static final int REPLACEAMOUNT = AttributesEnum.ReplaceAmount.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int TXTSUMPARTCOST = AttributesEnum.txtSumPartCost.index();
    public static final int TXTDISCOUNT = AttributesEnum.txtDiscount.index();
    public static final int TXTRECEIVED = AttributesEnum.txtReceived.index();
    public static final int TXTTOTAL = AttributesEnum.txtTotal.index();
    public static final int SRVINVITEMS = AttributesEnum.SrvInvItems.index();
    public static final int SRVJOBCARD = AttributesEnum.SrvJobcard.index();
    public static final int ACCSRVINVOICEITEMSRVPARTDETAIL = AttributesEnum.AccSrvInvoiceItemSrvPartDetail.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvInvoiceImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("dgcom.model.eo.srv.SrvInvoice");
    }


    /**
     * Gets the attribute value for SrvInvno, using the alias name SrvInvno.
     * @return the value of SrvInvno
     */
    public String getSrvInvno() {
        return (String) getAttributeInternal(SRVINVNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrvInvno.
     * @param value value to set the SrvInvno
     */
    public void setSrvInvno(String value) {
        setAttributeInternal(SRVINVNO, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for Jobcardno, using the alias name Jobcardno.
     * @return the value of Jobcardno
     */
    public String getJobcardno() {
        return (String) getAttributeInternal(JOBCARDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jobcardno.
     * @param value value to set the Jobcardno
     */
    public void setJobcardno(String value) {
        setAttributeInternal(JOBCARDNO, value);
        
        try {
            
            getAccSrvInvoiceItemSrvPartDetail().setNamedWhereClauseParam("P_ADF_JOBCARDNO", value);
            getAccSrvInvoiceItemSrvPartDetail().executeQuery();
            getAccSrvInvoiceItemSrvPartDetail().first();
            ApplicationModule am=this.getDBTransaction().getRootApplicationModule();
            
            ViewObject vo=am.findViewObject("SrvInvItemsDETCRUD");
            while(getSrvInvItems().getRowCount()>0) {
                getSrvInvItems().first().remove();
            }
            vo.executeQuery();
            getAccSrvInvoiceItemSrvPartDetail().setRangeSize(-1);
            if (getAccSrvInvoiceItemSrvPartDetail().getRowCount()>0) {
                Row r;
               for (int i = 0; i < getAccSrvInvoiceItemSrvPartDetail().getRowCount(); i++) {
                    r=this.getSrvInvItems().createRow();
                    r.setAttribute("Partid", getAccSrvInvoiceItemSrvPartDetail().getCurrentRow().getAttribute("Partid"));
                    r.setAttribute("Qty", getAccSrvInvoiceItemSrvPartDetail().getCurrentRow().getAttribute("Qty"));
                    r.setAttribute("Rate", getAccSrvInvoiceItemSrvPartDetail().getCurrentRow().getAttribute("Rate"));
                    r.setAttribute("SrvInvno", getSrvInvno());
                    getSrvInvItems().insertRow(r);
                    vo.executeQuery();
                    System.out.println(getSrvInvItems().getRowCount()+ " VO is towcount");
                    System.out.println(r.getAttribute("SrvInvno")+ "SrvInvno");
                   if (getAccSrvInvoiceItemSrvPartDetail().hasNext()) {
                       getAccSrvInvoiceItemSrvPartDetail().next();
                   }
                }
            }


        } catch (NullPointerException e) {
            
        }
        
    }

    /**
     * Gets the attribute value for Reasonid, using the alias name Reasonid.
     * @return the value of Reasonid
     */
    public String getReasonid() {
        return (String) getAttributeInternal(REASONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Reasonid.
     * @param value value to set the Reasonid
     */
    public void setReasonid(String value) {
        setAttributeInternal(REASONID, value);
    }

    /**
     * Gets the attribute value for InvDate, using the alias name InvDate.
     * @return the value of InvDate
     */
    public Date getInvDate() {
        return (Date) getAttributeInternal(INVDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvDate.
     * @param value value to set the InvDate
     */
    public void setInvDate(Date value) {
        setAttributeInternal(INVDATE, value);
    }

    /**
     * Gets the attribute value for Charges, using the alias name Charges.
     * @return the value of Charges
     */
    public BigDecimal getCharges() {
        return (BigDecimal) getAttributeInternal(CHARGES);
    }

    /**
     * Sets <code>value</code> as the attribute value for Charges.
     * @param value value to set the Charges
     */
    public void setCharges(BigDecimal value) {
        setAttributeInternal(CHARGES, value);
    }

    /**
     * Gets the attribute value for Discount, using the alias name Discount.
     * @return the value of Discount
     */
    public BigDecimal getDiscount() {
        return (BigDecimal) getAttributeInternal(DISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Discount.
     * @param value value to set the Discount
     */
    public void setDiscount(BigDecimal value) {
        setAttributeInternal(DISCOUNT, value);
    }

    /**
     * Gets the attribute value for Received, using the alias name Received.
     * @return the value of Received
     */
    public BigDecimal getReceived() {
        return (BigDecimal) getAttributeInternal(RECEIVED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Received.
     * @param value value to set the Received
     */
    public void setReceived(BigDecimal value) {
        setAttributeInternal(RECEIVED, value);
    }

    /**
     * Gets the attribute value for Rcptmode, using the alias name Rcptmode.
     * @return the value of Rcptmode
     */
    public String getRcptmode() {
        return (String) getAttributeInternal(RCPTMODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rcptmode.
     * @param value value to set the Rcptmode
     */
    public void setRcptmode(String value) {
        setAttributeInternal(RCPTMODE, value);
    }

    /**
     * Gets the attribute value for Referno, using the alias name Referno.
     * @return the value of Referno
     */
    public String getReferno() {
        return (String) getAttributeInternal(REFERNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Referno.
     * @param value value to set the Referno
     */
    public void setReferno(String value) {
        setAttributeInternal(REFERNO, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the value of Posted
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for Postedby, using the alias name Postedby.
     * @return the value of Postedby
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Postedby.
     * @param value value to set the Postedby
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for RecAmnt, using the alias name RecAmnt.
     * @return the value of RecAmnt
     */
    public BigDecimal getRecAmnt() {
        return (BigDecimal) getAttributeInternal(RECAMNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for RecAmnt.
     * @param value value to set the RecAmnt
     */
    public void setRecAmnt(BigDecimal value) {
        setAttributeInternal(RECAMNT, value);
    }

    /**
     * Gets the attribute value for ReceAmnt, using the alias name ReceAmnt.
     * @return the value of ReceAmnt
     */
    public BigDecimal getReceAmnt() {
        return (BigDecimal) getAttributeInternal(RECEAMNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceAmnt.
     * @param value value to set the ReceAmnt
     */
    public void setReceAmnt(BigDecimal value) {
        setAttributeInternal(RECEAMNT, value);
    }

    /**
     * Gets the attribute value for InvAmnt, using the alias name InvAmnt.
     * @return the value of InvAmnt
     */
    public BigDecimal getInvAmnt() {
        return (BigDecimal) getAttributeInternal(INVAMNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for InvAmnt.
     * @param value value to set the InvAmnt
     */
    public void setInvAmnt(BigDecimal value) {
        setAttributeInternal(INVAMNT, value);
    }

    /**
     * Gets the attribute value for DocTypeId, using the alias name DocTypeId.
     * @return the value of DocTypeId
     */
    public String getDocTypeId() {
        return (String) getAttributeInternal(DOCTYPEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocTypeId.
     * @param value value to set the DocTypeId
     */
    public void setDocTypeId(String value) {
        setAttributeInternal(DOCTYPEID, value);
    }

    /**
     * Gets the attribute value for PrevDoctype, using the alias name PrevDoctype.
     * @return the value of PrevDoctype
     */
    public String getPrevDoctype() {
        return (String) getAttributeInternal(PREVDOCTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrevDoctype.
     * @param value value to set the PrevDoctype
     */
    public void setPrevDoctype(String value) {
        setAttributeInternal(PREVDOCTYPE, value);
    }

    /**
     * Gets the attribute value for PrevDocid, using the alias name PrevDocid.
     * @return the value of PrevDocid
     */
    public String getPrevDocid() {
        return (String) getAttributeInternal(PREVDOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrevDocid.
     * @param value value to set the PrevDocid
     */
    public void setPrevDocid(String value) {
        setAttributeInternal(PREVDOCID, value);
    }

    /**
     * Gets the attribute value for ReceDisc, using the alias name ReceDisc.
     * @return the value of ReceDisc
     */
    public BigDecimal getReceDisc() {
        return (BigDecimal) getAttributeInternal(RECEDISC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceDisc.
     * @param value value to set the ReceDisc
     */
    public void setReceDisc(BigDecimal value) {
        setAttributeInternal(RECEDISC, value);
    }

    /**
     * Gets the attribute value for ChrgesDiscount, using the alias name ChrgesDiscount.
     * @return the value of ChrgesDiscount
     */
    public BigDecimal getChrgesDiscount() {
        return (BigDecimal) getAttributeInternal(CHRGESDISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ChrgesDiscount.
     * @param value value to set the ChrgesDiscount
     */
    public void setChrgesDiscount(BigDecimal value) {
        setAttributeInternal(CHRGESDISCOUNT, value);
    }

    /**
     * Gets the attribute value for PartDiscount, using the alias name PartDiscount.
     * @return the value of PartDiscount
     */
    public BigDecimal getPartDiscount() {
        return (BigDecimal) getAttributeInternal(PARTDISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for PartDiscount.
     * @param value value to set the PartDiscount
     */
    public void setPartDiscount(BigDecimal value) {
        setAttributeInternal(PARTDISCOUNT, value);
    }

    /**
     * Gets the attribute value for Chk, using the alias name Chk.
     * @return the value of Chk
     */
    public String getChk() {
        return (String) getAttributeInternal(CHK);
    }

    /**
     * Sets <code>value</code> as the attribute value for Chk.
     * @param value value to set the Chk
     */
    public void setChk(String value) {
        setAttributeInternal(CHK, value);
    }

    /**
     * Gets the attribute value for ReplaceAmount, using the alias name ReplaceAmount.
     * @return the value of ReplaceAmount
     */
    public BigDecimal getReplaceAmount() {
        return (BigDecimal) getAttributeInternal(REPLACEAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReplaceAmount.
     * @param value value to set the ReplaceAmount
     */
    public void setReplaceAmount(BigDecimal value) {
        setAttributeInternal(REPLACEAMOUNT, value);
    }

    /**
     * Gets the attribute value for IsMigrated, using the alias name IsMigrated.
     * @return the value of IsMigrated
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsMigrated.
     * @param value value to set the IsMigrated
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MigratedDate, using the alias name MigratedDate.
     * @return the value of MigratedDate
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MigratedDate.
     * @param value value to set the MigratedDate
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for txtSumPartCost, using the alias name txtSumPartCost.
     * @return the value of txtSumPartCost
     */
    public Integer gettxtSumPartCost() {
        return (Integer) getAttributeInternal(TXTSUMPARTCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtSumPartCost.
     * @param value value to set the txtSumPartCost
     */
    public void settxtSumPartCost(Integer value) {
        setAttributeInternal(TXTSUMPARTCOST, value);
    }

    /**
     * Gets the attribute value for txtDiscount, using the alias name txtDiscount.
     * @return the value of txtDiscount
     */
    public Integer gettxtDiscount() {
        return (Integer) getAttributeInternal(TXTDISCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtDiscount.
     * @param value value to set the txtDiscount
     */
    public void settxtDiscount(Integer value) {
        setAttributeInternal(TXTDISCOUNT, value);
    }

    /**
     * Gets the attribute value for txtReceived, using the alias name txtReceived.
     * @return the value of txtReceived
     */
    public BigDecimal gettxtReceived() {
        return (BigDecimal) getAttributeInternal(TXTRECEIVED);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtReceived.
     * @param value value to set the txtReceived
     */
    public void settxtReceived(BigDecimal value) {
        setAttributeInternal(TXTRECEIVED, value);
    }

    /**
     * Gets the attribute value for txtTotal, using the alias name txtTotal.
     * @return the value of txtTotal
     */
    public Integer gettxtTotal() {
        return (Integer) getAttributeInternal(TXTTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtTotal.
     * @param value value to set the txtTotal
     */
    public void settxtTotal(Integer value) {
        setAttributeInternal(TXTTOTAL, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSrvInvItems() {
        return (RowIterator) getAttributeInternal(SRVINVITEMS);
    }


    /**
     * @return the associated entity SrvJobcardImpl.
     */
    public SrvJobcardImpl getSrvJobcard() {
        return (SrvJobcardImpl) getAttributeInternal(SRVJOBCARD);
    }

    /**
     * Sets <code>value</code> as the associated entity SrvJobcardImpl.
     */
    public void setSrvJobcard(SrvJobcardImpl value) {
        setAttributeInternal(SRVJOBCARD, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvInvoiceItemSrvPartDetail.
     */
    public RowSet getAccSrvInvoiceItemSrvPartDetail() {
        return (RowSet) getAttributeInternal(ACCSRVINVOICEITEMSRVPARTDETAIL);
    }


    /**
     * @param srvInvno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String srvInvno) {
        return new Key(new Object[] { srvInvno });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {

        if (operation==DML_INSERT) {
            ApplicationModule am=this.getDBTransaction().getRootApplicationModule();
            ViewObject        vo=am.findViewObject("myServiceInvPK");
            if (vo!=null)
                {
                   vo.remove();     
                }
            vo=am.createViewObjectFromQueryStmt("myServiceInvPK",
                                                "Select 2||'"+getLocationid()+"'||'"+DigicomClass.doGetFormattedDate(getInvDate().toString(), "yyMM")+"'||Lpad(nvl(max(to_number(substr(SRV_INVNO,-4)))+1,1) ,4,'0') as PK \n"+
                                                "from SRV_INVOICE \n"+
                                                "Where to_char(inv_date,'rrmm') ='"+ DigicomClass.doGetFormattedDate(getInvDate().toString(), "yyMM")+"' \n"+
                                                "and locationid = '"+getLocationid()+"'");
            vo.executeQuery();
            setSrvInvno(vo.first().getAttribute(0).toString());
            /*for (int i = 0; i < getSrvInvItems().getRowCount(); i++) {
                getSrvInvItems().getRowAtRangeIndex(i).setAttribute("SrvInvno", vo.first().getAttribute(0).toString());
                System.out.println(i);
           }*/

        }
        super.doDML(operation, e);
    }
}

