package dgcom.model.eo.srv;

import dgcom.model.stand.DigicomEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 22 10:49:03 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobsymptomImpl extends DigicomEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SymptomId,
        Jobcardno,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        RowID,
        Jobcardseq,
        SrvJobcard,
        SrvIssuance,
        SrvJobsymptomSEQ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SYMPTOMID = AttributesEnum.SymptomId.index();
    public static final int JOBCARDNO = AttributesEnum.Jobcardno.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int JOBCARDSEQ = AttributesEnum.Jobcardseq.index();
    public static final int SRVJOBCARD = AttributesEnum.SrvJobcard.index();
    public static final int SRVISSUANCE = AttributesEnum.SrvIssuance.index();
    public static final int SRVJOBSYMPTOMSEQ = AttributesEnum.SrvJobsymptomSEQ.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobsymptomImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("dgcom.model.eo.srv.SrvJobsymptom");
    }


    /**
     * Gets the attribute value for SymptomId, using the alias name SymptomId.
     * @return the value of SymptomId
     */
    public String getSymptomId() {
        return (String) getAttributeInternal(SYMPTOMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SymptomId.
     * @param value value to set the SymptomId
     */
    public void setSymptomId(String value) {
        setAttributeInternal(SYMPTOMID, value);
    }

    /**
     * Gets the attribute value for Jobcardno, using the alias name Jobcardno.
     * @return the value of Jobcardno
     */
    public String getJobcardno() {
        return (String) getAttributeInternal(JOBCARDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jobcardno.
     * @param value value to set the Jobcardno
     */
    public void setJobcardno(String value) {
        setAttributeInternal(JOBCARDNO, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for RowID, using the alias name RowID.
     * @return the value of RowID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Gets the attribute value for Jobcardseq, using the alias name Jobcardseq.
     * @return the value of Jobcardseq
     */
    public Integer getJobcardseq() {
        return (Integer) getAttributeInternal(JOBCARDSEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jobcardseq.
     * @param value value to set the Jobcardseq
     */
    public void setJobcardseq(Integer value) {
        setAttributeInternal(JOBCARDSEQ, value);
    }

    /**
     * @return the associated entity SrvJobcardImpl.
     */
    public SrvJobcardImpl getSrvJobcard() {
        return (SrvJobcardImpl) getAttributeInternal(SRVJOBCARD);
    }

    /**
     * Sets <code>value</code> as the associated entity SrvJobcardImpl.
     */
    public void setSrvJobcard(SrvJobcardImpl value) {
        setAttributeInternal(SRVJOBCARD, value);
    }

    /**
     * @return the associated entity SrvIssuanceImpl.
     */
    public SrvIssuanceImpl getSrvIssuance() {
        return (SrvIssuanceImpl) getAttributeInternal(SRVISSUANCE);
    }

    /**
     * Sets <code>value</code> as the associated entity SrvIssuanceImpl.
     */
    public void setSrvIssuance(SrvIssuanceImpl value) {
        setAttributeInternal(SRVISSUANCE, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SrvJobsymptomSEQ.
     */
    public RowSet getSrvJobsymptomSEQ() {
        return (RowSet) getAttributeInternal(SRVJOBSYMPTOMSEQ);
    }


    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
          if (operation==DML_INSERT && getSymptomId()==null) {
              remove();
               return;
          }       
          
         if (operation==DML_INSERT /*&& getJobcardno().contains("-")*/) {
             System.out.println("one");
             populateAttributeAsChanged(JOBCARDNO, getSrvJobcard().getAttribute("Jobcardno"));
           System.out.println("two");
             
//            setJobcardno(this.getDBTransaction().getRootApplicationModule().findViewObject("SrvJobcardCRUD").getCurrentRow().getAttribute("Jobcardno").toString());
       } 
        super.doDML(operation, e);
    }
}

