package dgcom.model.eo.srv;

import dgcom.model.eo.inv.InItemsImpl;
import dgcom.model.stand.DigicomClass;
import dgcom.model.stand.DigicomEntityImpl;

import oracle.jbo.ApplicationModule;
import oracle.jbo.AttributeList;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 20 16:20:18 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvRfwdetlImpl extends DigicomEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Rfwid,
        Jobcardno,
        Startdate,
        Expdate,
        NewItemid,
        ImeiNo,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Itemid,
        Rowid,
        txtNewItemIdDesc,
        txtItemidDesc,
        txtWarranty,
        txtJobcardItemid,
        txtImeiSerial,
        SrvRfwarranty,
        InItems,
        InItems1,
        SrvJobcard;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int RFWID = AttributesEnum.Rfwid.index();
    public static final int JOBCARDNO = AttributesEnum.Jobcardno.index();
    public static final int STARTDATE = AttributesEnum.Startdate.index();
    public static final int EXPDATE = AttributesEnum.Expdate.index();
    public static final int NEWITEMID = AttributesEnum.NewItemid.index();
    public static final int IMEINO = AttributesEnum.ImeiNo.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ROWID = AttributesEnum.Rowid.index();
    public static final int TXTNEWITEMIDDESC = AttributesEnum.txtNewItemIdDesc.index();
    public static final int TXTITEMIDDESC = AttributesEnum.txtItemidDesc.index();
    public static final int TXTWARRANTY = AttributesEnum.txtWarranty.index();
    public static final int TXTJOBCARDITEMID = AttributesEnum.txtJobcardItemid.index();
    public static final int TXTIMEISERIAL = AttributesEnum.txtImeiSerial.index();
    public static final int SRVRFWARRANTY = AttributesEnum.SrvRfwarranty.index();
    public static final int INITEMS = AttributesEnum.InItems.index();
    public static final int INITEMS1 = AttributesEnum.InItems1.index();
    public static final int SRVJOBCARD = AttributesEnum.SrvJobcard.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvRfwdetlImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("dgcom.model.eo.srv.SrvRfwdetl");
    }

    /**
     * Gets the attribute value for Rfwid, using the alias name Rfwid.
     * @return the value of Rfwid
     */
    public String getRfwid() {
        return (String) getAttributeInternal(RFWID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rfwid.
     * @param value value to set the Rfwid
     */
    public void setRfwid(String value) {
        setAttributeInternal(RFWID, value);
    }

    /**
     * Gets the attribute value for Jobcardno, using the alias name Jobcardno.
     * @return the value of Jobcardno
     */
    public String getJobcardno() {
        return (String) getAttributeInternal(JOBCARDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jobcardno.
     * @param value value to set the Jobcardno
     */
    public void setJobcardno(String value) {
        setAttributeInternal(JOBCARDNO, value);
        System.out.println("gettxtJobcardItemid:"+gettxtJobcardItemid());
        if (value!=null) {
            setItemid(gettxtJobcardItemid());
       }
    }

    /**
     * Gets the attribute value for Startdate, using the alias name Startdate.
     * @return the value of Startdate
     */
    public Date getStartdate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Startdate.
     * @param value value to set the Startdate
     */
    public void setStartdate(Date value) {
        setAttributeInternal(STARTDATE, value);
        setExpdate(DigicomClass.doGetAddedDate(DigicomClass.doGetAddeddMonths(value,12) ,-1));
        
    }

    /**
     * Gets the attribute value for Expdate, using the alias name Expdate.
     * @return the value of Expdate
     */
    public Date getExpdate() {
        return (Date) getAttributeInternal(EXPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Expdate.
     * @param value value to set the Expdate
     */
    public void setExpdate(Date value) {
        setAttributeInternal(EXPDATE, value);
    }

    /**
     * Gets the attribute value for NewItemid, using the alias name NewItemid.
     * @return the value of NewItemid
     */
    public String getNewItemid() {
        return (String) getAttributeInternal(NEWITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for NewItemid.
     * @param value value to set the NewItemid
     */
    public void setNewItemid(String value) {
        setAttributeInternal(NEWITEMID, value);
    }

    /**
     * Gets the attribute value for ImeiNo, using the alias name ImeiNo.
     * @return the value of ImeiNo
     */
    public Long getImeiNo() {
        return (Long) getAttributeInternal(IMEINO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImeiNo.
     * @param value value to set the ImeiNo
     */
    public void setImeiNo(Long value) {
        
        if (gettxtImeiSerial()!=null && gettxtImeiSerial().equals("S")) {
            ApplicationModule am=this.getDBTransaction().getRootApplicationModule();
            ViewObject vo=am.findViewObject("VImei");
            if (vo!=null) {
                vo.remove();
           }
            vo=am.createViewObjectFromQueryStmt("VImei", "select imei from item_imei_info f where serial_no='"+value+"'");
            vo.executeQuery();
            //setImeiNo(Long.parseLong(vo.first().getAttribute(0).toString()));
            setAttributeInternal(IMEINO, Long.parseLong(vo.first().getAttribute(0).toString()));
       }
        else
        {
            setAttributeInternal(IMEINO, value);
            }
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
        String  reason=getSrvRfwarranty().getAttribute("Reason").toString();
        if (reason.equals("D")||reason.equals("MM")||reason.equals("CL")) {
            setNewItemid(value);
       }
    }

    /**
     * Gets the attribute value for Rowid, using the alias name Rowid.
     * @return the value of Rowid
     */
    public RowID getRowid() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Gets the attribute value for txtNewItemIdDesc, using the alias name txtNewItemIdDesc.
     * @return the value of txtNewItemIdDesc
     */
    public String gettxtNewItemIdDesc() {
        return (String) getAttributeInternal(TXTNEWITEMIDDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtNewItemIdDesc.
     * @param value value to set the txtNewItemIdDesc
     */
    public void settxtNewItemIdDesc(String value) {
        setAttributeInternal(TXTNEWITEMIDDESC, value);
    }

    /**
     * Gets the attribute value for txtItemidDesc, using the alias name txtItemidDesc.
     * @return the value of txtItemidDesc
     */
    public String gettxtItemidDesc() {
        return (String) getAttributeInternal(TXTITEMIDDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtItemidDesc.
     * @param value value to set the txtItemidDesc
     */
    public void settxtItemidDesc(String value) {
        setAttributeInternal(TXTITEMIDDESC, value);
    }

    /**
     * Gets the attribute value for txtWarranty, using the alias name txtWarranty.
     * @return the value of txtWarranty
     */
    public String gettxtWarranty() {
        return (String) getAttributeInternal(TXTWARRANTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtWarranty.
     * @param value value to set the txtWarranty
     */
    public void settxtWarranty(String value) {
        setAttributeInternal(TXTWARRANTY, value);
    }

    /**
     * Gets the attribute value for txtJobcardItemid, using the alias name txtJobcardItemid.
     * @return the value of txtJobcardItemid
     */
    public String gettxtJobcardItemid() {
        return (String) getAttributeInternal(TXTJOBCARDITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtJobcardItemid.
     * @param value value to set the txtJobcardItemid
     */
    public void settxtJobcardItemid(String value) {
        setAttributeInternal(TXTJOBCARDITEMID, value);
    }

    /**
     * Gets the attribute value for txtImeiSerial, using the alias name txtImeiSerial.
     * @return the value of txtImeiSerial
     */
    public String gettxtImeiSerial() {
        return (String) getAttributeInternal(TXTIMEISERIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtImeiSerial.
     * @param value value to set the txtImeiSerial
     */
    public void settxtImeiSerial(String value) {
        setAttributeInternal(TXTIMEISERIAL, value);
    }

    /**
     * @return the associated entity dgcom.model.stand.DigicomEntityImpl.
     */
    public SrvRfwarrantyImpl getSrvRfwarranty() {
        return (SrvRfwarrantyImpl) getAttributeInternal(SRVRFWARRANTY);
    }

    /**
     * Sets <code>value</code> as the associated entity dgcom.model.stand.DigicomEntityImpl.
     */
    public void setSrvRfwarranty(SrvRfwarrantyImpl value) {
        setAttributeInternal(SRVRFWARRANTY, value);
    }

    /**
     * @return the associated entity dgcom.model.eo.inv.InItemsImpl.
     */
    public InItemsImpl getInItems() {
        return (InItemsImpl) getAttributeInternal(INITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity dgcom.model.eo.inv.InItemsImpl.
     */
    public void setInItems(InItemsImpl value) {
        setAttributeInternal(INITEMS, value);
    }

    /**
     * @return the associated entity dgcom.model.eo.inv.InItemsImpl.
     */
    public InItemsImpl getInItems1() {
        return (InItemsImpl) getAttributeInternal(INITEMS1);
    }

    /**
     * Sets <code>value</code> as the associated entity dgcom.model.eo.inv.InItemsImpl.
     */
    public void setInItems1(InItemsImpl value) {
        setAttributeInternal(INITEMS1, value);
    }

    /**
     * @return the associated entity SrvJobcardImpl.
     */
    public SrvJobcardImpl getSrvJobcard() {
        return (SrvJobcardImpl) getAttributeInternal(SRVJOBCARD);
    }

    /**
     * Sets <code>value</code> as the associated entity SrvJobcardImpl.
     */
    public void setSrvJobcard(SrvJobcardImpl value) {
        setAttributeInternal(SRVJOBCARD, value);
    }


    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT && getItemid()==null && getJobcardno() ==null && getNewItemid()==null) {
            remove();
            return;
       }
        super.doDML(operation, e);
    }
}

