package dgcom.model.eo.srv;

import dgcom.model.eo.inv.InItemsImpl;
import dgcom.model.stand.DigicomClass;
import dgcom.model.stand.DigicomEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.ApplicationModule;
import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 28 10:32:27 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvSetReplacementImpl extends DigicomEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SrId,
        Locationid,
        Jobcardno,
        Itemid,
        SrDate,
        NewImeiNo,
        Amount,
        Remarks,
        PrevDoctype,
        PrevDocid,
        Posted,
        Postedby,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        IsMigrated,
        MigratedDate,
        txtProdId,
        InRate,
        InStoreid,
        OutRate,
        OutStoreid,
        txtOutStoreName,
        txtInStoreName,
        txtJobcardItemId,
        txtModelName,
        SrvJobcard,
        AllStores,
        AllStores1,
        InItems,
        AccAllStoresInStoreId,
        AccSoProdLocPriceProductLocation,
        AccItemImeiInfo;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SRID = AttributesEnum.SrId.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int JOBCARDNO = AttributesEnum.Jobcardno.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int SRDATE = AttributesEnum.SrDate.index();
    public static final int NEWIMEINO = AttributesEnum.NewImeiNo.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int PREVDOCTYPE = AttributesEnum.PrevDoctype.index();
    public static final int PREVDOCID = AttributesEnum.PrevDocid.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int TXTPRODID = AttributesEnum.txtProdId.index();
    public static final int INRATE = AttributesEnum.InRate.index();
    public static final int INSTOREID = AttributesEnum.InStoreid.index();
    public static final int OUTRATE = AttributesEnum.OutRate.index();
    public static final int OUTSTOREID = AttributesEnum.OutStoreid.index();
    public static final int TXTOUTSTORENAME = AttributesEnum.txtOutStoreName.index();
    public static final int TXTINSTORENAME = AttributesEnum.txtInStoreName.index();
    public static final int TXTJOBCARDITEMID = AttributesEnum.txtJobcardItemId.index();
    public static final int TXTMODELNAME = AttributesEnum.txtModelName.index();
    public static final int SRVJOBCARD = AttributesEnum.SrvJobcard.index();
    public static final int ALLSTORES = AttributesEnum.AllStores.index();
    public static final int ALLSTORES1 = AttributesEnum.AllStores1.index();
    public static final int INITEMS = AttributesEnum.InItems.index();
    public static final int ACCALLSTORESINSTOREID = AttributesEnum.AccAllStoresInStoreId.index();
    public static final int ACCSOPRODLOCPRICEPRODUCTLOCATION = AttributesEnum.AccSoProdLocPriceProductLocation.index();
    public static final int ACCITEMIMEIINFO = AttributesEnum.AccItemImeiInfo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvSetReplacementImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("dgcom.model.eo.srv.SrvSetReplacement");
    }


    /**
     * Gets the attribute value for SrId, using the alias name SrId.
     * @return the value of SrId
     */
    public String getSrId() {
        return (String) getAttributeInternal(SRID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrId.
     * @param value value to set the SrId
     */
    public void setSrId(String value) {
        setAttributeInternal(SRID, value);
    }

    /**
     * Gets the attribute value for Locationid, using the alias name Locationid.
     * @return the value of Locationid
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locationid.
     * @param value value to set the Locationid
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
        if (value!=null) {
            getAccAllStoresInStoreId().setNamedWhereClauseParam("P_ADF_LOCATIONID", value);
            getAccAllStoresInStoreId().executeQuery();
            getAccAllStoresInStoreId().getViewObject().setWhereClause("store_name='CUSTOMER REPLACEMENT'");
            getAccAllStoresInStoreId().executeQuery();
            setInStoreid(getAccAllStoresInStoreId().first().getAttribute("Storeid").toString());
            /* getAccAllStoresInStoreId().getViewObject().setWhereClause("");
            getAccAllStoresInStoreId().executeQuery(); */
        }
        
    }

    /**
     * Gets the attribute value for Jobcardno, using the alias name Jobcardno.
     * @return the value of Jobcardno
     */
    public String getJobcardno() {
        return (String) getAttributeInternal(JOBCARDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Jobcardno.
     * @param value value to set the Jobcardno
     */
    public void setJobcardno(String value) {
        setAttributeInternal(JOBCARDNO, value);
        getAccSoProdLocPriceProductLocation().setNamedWhereClauseParam("P_ADF_ITEMID", gettxtJobcardItemId());
        getAccSoProdLocPriceProductLocation().executeQuery();
        setInRate(new BigDecimal(getAccSoProdLocPriceProductLocation().first().getAttribute("DelearPrice").toString()));
        System.out.println(getInRate());
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
        getAccSoProdLocPriceProductLocation().setNamedWhereClauseParam("P_ADF_ITEMID", value);
        getAccSoProdLocPriceProductLocation().executeQuery();
        setOutRate(new BigDecimal(getAccSoProdLocPriceProductLocation().first().getAttribute("DelearPrice").toString()));
        System.out.println(getOutRate());        
    }

    /**
     * Gets the attribute value for SrDate, using the alias name SrDate.
     * @return the value of SrDate
     */
    public Date getSrDate() {
        return (Date) getAttributeInternal(SRDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SrDate.
     * @param value value to set the SrDate
     */
    public void setSrDate(Date value) {
        setAttributeInternal(SRDATE, value);
    }

    /**
     * Gets the attribute value for NewImeiNo, using the alias name NewImeiNo.
     * @return the value of NewImeiNo
     */
    public String getNewImeiNo() {
        return (String) getAttributeInternal(NEWIMEINO);
    }

    /**
     * Sets <code>value</code> as the attribute value for NewImeiNo.
     * @param value value to set the NewImeiNo
     */
    public void setNewImeiNo(String value) {
        setAttributeInternal(NEWIMEINO, value);
    }

    /**
     * Gets the attribute value for Amount, using the alias name Amount.
     * @return the value of Amount
     */
    public BigDecimal getAmount() {
        return (BigDecimal) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Amount.
     * @param value value to set the Amount
     */
    public void setAmount(BigDecimal value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for PrevDoctype, using the alias name PrevDoctype.
     * @return the value of PrevDoctype
     */
    public String getPrevDoctype() {
        return (String) getAttributeInternal(PREVDOCTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrevDoctype.
     * @param value value to set the PrevDoctype
     */
    public void setPrevDoctype(String value) {
        setAttributeInternal(PREVDOCTYPE, value);
    }

    /**
     * Gets the attribute value for PrevDocid, using the alias name PrevDocid.
     * @return the value of PrevDocid
     */
    public String getPrevDocid() {
        return (String) getAttributeInternal(PREVDOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PrevDocid.
     * @param value value to set the PrevDocid
     */
    public void setPrevDocid(String value) {
        setAttributeInternal(PREVDOCID, value);
    }

    /**
     * Gets the attribute value for Posted, using the alias name Posted.
     * @return the value of Posted
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Posted.
     * @param value value to set the Posted
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for Postedby, using the alias name Postedby.
     * @return the value of Postedby
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Postedby.
     * @param value value to set the Postedby
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for Createdby, using the alias name Createdby.
     * @return the value of Createdby
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Createdby.
     * @param value value to set the Createdby
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for Modifiedby, using the alias name Modifiedby.
     * @return the value of Modifiedby
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Modifiedby.
     * @param value value to set the Modifiedby
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for ModifiedDate, using the alias name ModifiedDate.
     * @return the value of ModifiedDate
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ModifiedDate.
     * @param value value to set the ModifiedDate
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for IsMigrated, using the alias name IsMigrated.
     * @return the value of IsMigrated
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsMigrated.
     * @param value value to set the IsMigrated
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MigratedDate, using the alias name MigratedDate.
     * @return the value of MigratedDate
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for MigratedDate.
     * @param value value to set the MigratedDate
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for txtProdId, using the alias name txtProdId.
     * @return the value of txtProdId
     */
    public String gettxtProdId() {
        return (String) getAttributeInternal(TXTPRODID);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtProdId.
     * @param value value to set the txtProdId
     */
    public void settxtProdId(String value) {
        setAttributeInternal(TXTPRODID, value);
    }

    /**
     * Gets the attribute value for InRate, using the alias name InRate.
     * @return the value of InRate
     */
    public BigDecimal getInRate() {
        return (BigDecimal) getAttributeInternal(INRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InRate.
     * @param value value to set the InRate
     */
    public void setInRate(BigDecimal value) {
        setAttributeInternal(INRATE, value);
    }

    /**
     * Gets the attribute value for InStoreid, using the alias name InStoreid.
     * @return the value of InStoreid
     */
    public String getInStoreid() {
        return (String) getAttributeInternal(INSTOREID);
    }

    /**
     * Sets <code>value</code> as the attribute value for InStoreid.
     * @param value value to set the InStoreid
     */
    public void setInStoreid(String value) {
        setAttributeInternal(INSTOREID, value);
    }

    /**
     * Gets the attribute value for OutRate, using the alias name OutRate.
     * @return the value of OutRate
     */
    public BigDecimal getOutRate() {
        return (BigDecimal) getAttributeInternal(OUTRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OutRate.
     * @param value value to set the OutRate
     */
    public void setOutRate(BigDecimal value) {
        setAttributeInternal(OUTRATE, value);
    }

    /**
     * Gets the attribute value for OutStoreid, using the alias name OutStoreid.
     * @return the value of OutStoreid
     */
    public String getOutStoreid() {
        return (String) getAttributeInternal(OUTSTOREID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OutStoreid.
     * @param value value to set the OutStoreid
     */
    public void setOutStoreid(String value) {
        setAttributeInternal(OUTSTOREID, value);
    }

    /**
     * Gets the attribute value for txtOutStoreName, using the alias name txtOutStoreName.
     * @return the value of txtOutStoreName
     */
    public String gettxtOutStoreName() {
        return (String) getAttributeInternal(TXTOUTSTORENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtOutStoreName.
     * @param value value to set the txtOutStoreName
     */
    public void settxtOutStoreName(String value) {
        setAttributeInternal(TXTOUTSTORENAME, value);
    }

    /**
     * Gets the attribute value for txtInStoreName, using the alias name txtInStoreName.
     * @return the value of txtInStoreName
     */
    public String gettxtInStoreName() {
        return (String) getAttributeInternal(TXTINSTORENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtInStoreName.
     * @param value value to set the txtInStoreName
     */
    public void settxtInStoreName(String value) {
        setAttributeInternal(TXTINSTORENAME, value);
    }

    /**
     * Gets the attribute value for txtJobcardItemId, using the alias name txtJobcardItemId.
     * @return the value of txtJobcardItemId
     */
    public String gettxtJobcardItemId() {
        return (String) getAttributeInternal(TXTJOBCARDITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtJobcardItemId.
     * @param value value to set the txtJobcardItemId
     */
    public void settxtJobcardItemId(String value) {
        setAttributeInternal(TXTJOBCARDITEMID, value);
    }

    /**
     * Gets the attribute value for txtModelName, using the alias name txtModelName.
     * @return the value of txtModelName
     */
    public String gettxtModelName() {
        return (String) getAttributeInternal(TXTMODELNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtModelName.
     * @param value value to set the txtModelName
     */
    public void settxtModelName(String value) {
        setAttributeInternal(TXTMODELNAME, value);
    }

    /**
     * @return the associated entity SrvJobcardImpl.
     */
    public SrvJobcardImpl getSrvJobcard() {
        return (SrvJobcardImpl) getAttributeInternal(SRVJOBCARD);
    }

    /**
     * Sets <code>value</code> as the associated entity SrvJobcardImpl.
     */
    public void setSrvJobcard(SrvJobcardImpl value) {
        setAttributeInternal(SRVJOBCARD, value);
    }


    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAllStores() {
        return (EntityImpl) getAttributeInternal(ALLSTORES);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAllStores(EntityImpl value) {
        setAttributeInternal(ALLSTORES, value);
    }

    /**
     * @return the associated entity oracle.jbo.server.EntityImpl.
     */
    public EntityImpl getAllStores1() {
        return (EntityImpl) getAttributeInternal(ALLSTORES1);
    }

    /**
     * Sets <code>value</code> as the associated entity oracle.jbo.server.EntityImpl.
     */
    public void setAllStores1(EntityImpl value) {
        setAttributeInternal(ALLSTORES1, value);
    }


    /**
     * @return the associated entity dgcom.model.eo.inv.InItemsImpl.
     */
    public InItemsImpl getInItems() {
        return (InItemsImpl) getAttributeInternal(INITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity dgcom.model.eo.inv.InItemsImpl.
     */
    public void setInItems(InItemsImpl value) {
        setAttributeInternal(INITEMS, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAllStoresInStoreId.
     */
    public RowSet getAccAllStoresInStoreId() {
        return (RowSet) getAttributeInternal(ACCALLSTORESINSTOREID);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccSoProdLocPriceProductLocation.
     */
    public RowSet getAccSoProdLocPriceProductLocation() {
        return (RowSet) getAttributeInternal(ACCSOPRODLOCPRICEPRODUCTLOCATION);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccItemImeiInfo.
     */
    public RowSet getAccItemImeiInfo() {
        return (RowSet) getAttributeInternal(ACCITEMIMEIINFO);
    }


    /**
     * @param srId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String srId) {
        return new Key(new Object[] { srId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation==DML_INSERT) {
            ApplicationModule am=this.getDBTransaction().getRootApplicationModule();
            ViewObject        vo=am.findViewObject("mySetReplacementPK");
            if (vo!=null)
                {
                   vo.remove();     
                }
            vo=am.createViewObjectFromQueryStmt("mySetReplacementPK",
                                                "Select 2||'"+getLocationid()+"'||'"+DigicomClass.doGetFormattedDate(getSrDate().toString(), "yyMM")+"'||Lpad(nvl(max(to_number(substr(SR_Id,-4)))+1,1) ,4,'0') as PK \n"+
                                                "from SRV_Set_Replacement \n"+
                                                "Where to_char(SR_DATE,'rrmm') ='"+ DigicomClass.doGetFormattedDate(getSrDate().toString(), "yyMM")+"' \n"+
                                                "and locationid = '"+getLocationid()+"'");
            vo.executeQuery();
            setSrId(vo.first().getAttribute(0).toString());
        }  
        super.doDML(operation, e);
    }
}

