package dgcom.model.qvo.srv;

import dgcom.model.qvo.srv.common.PartExplorePartWiseQVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 11 16:40:49 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PartExplorePartWiseQVOImpl extends ViewObjectImpl implements PartExplorePartWiseQVO {
    /**
     * This is the default constructor (do not remove).
     */
    public PartExplorePartWiseQVOImpl() {
    }

    /**
     * Returns the bind variable value for P_ADF_ITEMID.
     * @return bind variable value for P_ADF_ITEMID
     */
    public String getP_ADF_ITEMID() {
        return (String) getNamedWhereClauseParam("P_ADF_ITEMID");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_ITEMID.
     * @param value value to bind as P_ADF_ITEMID
     */
    public void setP_ADF_ITEMID(String value) {
        setNamedWhereClauseParam("P_ADF_ITEMID", value);
    }

    /**
     * Returns the bind variable value for P_ADF_PARTID.
     * @return bind variable value for P_ADF_PARTID
     */
    public String getP_ADF_PARTID() {
        return (String) getNamedWhereClauseParam("P_ADF_PARTID");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_PARTID.
     * @param value value to bind as P_ADF_PARTID
     */
    public void setP_ADF_PARTID(String value) {
        setNamedWhereClauseParam("P_ADF_PARTID", value);
    }

    /**
     * Returns the bind variable value for P_ADF_CAT_ID.
     * @return bind variable value for P_ADF_CAT_ID
     */
    public String getP_ADF_CAT_ID() {
        return (String) getNamedWhereClauseParam("P_ADF_CAT_ID");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_CAT_ID.
     * @param value value to bind as P_ADF_CAT_ID
     */
    public void setP_ADF_CAT_ID(String value) {
        setNamedWhereClauseParam("P_ADF_CAT_ID", value);
    }

    /**
     * Returns the bind variable value for P_ADF_LOCATIONID.
     * @return bind variable value for P_ADF_LOCATIONID
     */
    public String getP_ADF_LOCATIONID() {
        return (String) getNamedWhereClauseParam("P_ADF_LOCATIONID");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_LOCATIONID.
     * @param value value to bind as P_ADF_LOCATIONID
     */
    public void setP_ADF_LOCATIONID(String value) {
        setNamedWhereClauseParam("P_ADF_LOCATIONID", value);
    }

    @Override
    public void executeEmptyRowSet() {
        // TODO Implement this method
        super.executeEmptyRowSet();
    }
}

