package dgcom.model.qvo.srv;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 09 12:11:38 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobCardLogCIC_0051QVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobCardLogCIC_0051QVOImpl() {
    }

    /**
     * Returns the bind variable value for P_ADF_JOBCARDNO.
     * @return bind variable value for P_ADF_JOBCARDNO
     */
    public String getP_ADF_JOBCARDNO() {
        return (String) getNamedWhereClauseParam("P_ADF_JOBCARDNO");
    }

    /**
     * Sets <code>value</code> for bind variable P_ADF_JOBCARDNO.
     * @param value value to bind as P_ADF_JOBCARDNO
     */
    public void setP_ADF_JOBCARDNO(String value) {
        setNamedWhereClauseParam("P_ADF_JOBCARDNO", value);
    }
    
}

