package dgcom.model.vo.srv;

import dgcom.model.eo.srv.SrvIretdetailImpl;
import dgcom.model.stand.DigicomViewRowImpl;

import java.math.BigDecimal;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 19 12:15:22 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvIretdetailVORowImpl extends DigicomViewRowImpl {


    public static final int ENTITY_SRVIRETDETAIL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Issueretid,
        Issuedetlid,
        Storeid,
        Qty,
        RejectQty,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Rowid,
        txtStoreTransTypeId,
        txtStoreId,
        txtStoreName,
        Issueretseq,
        SrvIssuereturnVO,
        AccSrvIretDetailStoreId,
        AccSrvIssueReturnDetailParts;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ISSUERETID = AttributesEnum.Issueretid.index();
    public static final int ISSUEDETLID = AttributesEnum.Issuedetlid.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int REJECTQTY = AttributesEnum.RejectQty.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int ROWID = AttributesEnum.Rowid.index();
    public static final int TXTSTORETRANSTYPEID = AttributesEnum.txtStoreTransTypeId.index();
    public static final int TXTSTOREID = AttributesEnum.txtStoreId.index();
    public static final int TXTSTORENAME = AttributesEnum.txtStoreName.index();
    public static final int ISSUERETSEQ = AttributesEnum.Issueretseq.index();
    public static final int SRVISSUERETURNVO = AttributesEnum.SrvIssuereturnVO.index();
    public static final int ACCSRVIRETDETAILSTOREID = AttributesEnum.AccSrvIretDetailStoreId.index();
    public static final int ACCSRVISSUERETURNDETAILPARTS = AttributesEnum.AccSrvIssueReturnDetailParts.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvIretdetailVORowImpl() {
    }

    /**
     * Gets SrvIretdetail entity object.
     * @return the SrvIretdetail
     */
    public SrvIretdetailImpl getSrvIretdetail() {
        return (SrvIretdetailImpl) getEntity(ENTITY_SRVIRETDETAIL);
    }

    /**
     * Gets the attribute value for ISSUERETID using the alias name Issueretid.
     * @return the ISSUERETID
     */
    public String getIssueretid() {
        return (String) getAttributeInternal(ISSUERETID);
    }

    /**
     * Sets <code>value</code> as attribute value for ISSUERETID using the alias name Issueretid.
     * @param value value to set the ISSUERETID
     */
    public void setIssueretid(String value) {
        setAttributeInternal(ISSUERETID, value);
    }

    /**
     * Gets the attribute value for ISSUEDETLID using the alias name Issuedetlid.
     * @return the ISSUEDETLID
     */
    public String getIssuedetlid() {
        return (String) getAttributeInternal(ISSUEDETLID);
    }

    /**
     * Sets <code>value</code> as attribute value for ISSUEDETLID using the alias name Issuedetlid.
     * @param value value to set the ISSUEDETLID
     */
    public void setIssuedetlid(String value) {
        setAttributeInternal(ISSUEDETLID, value);
    }

    /**
     * Gets the attribute value for STOREID using the alias name Storeid.
     * @return the STOREID
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for STOREID using the alias name Storeid.
     * @param value value to set the STOREID
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for QTY using the alias name Qty.
     * @return the QTY
     */
    public BigDecimal getQty() {
        return (BigDecimal) getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as attribute value for QTY using the alias name Qty.
     * @param value value to set the QTY
     */
    public void setQty(BigDecimal value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for REJECT_QTY using the alias name RejectQty.
     * @return the REJECT_QTY
     */
    public BigDecimal getRejectQty() {
        return (BigDecimal) getAttributeInternal(REJECTQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for REJECT_QTY using the alias name RejectQty.
     * @param value value to set the REJECT_QTY
     */
    public void setRejectQty(BigDecimal value) {
        setAttributeInternal(REJECTQTY, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name Rowid.
     * @return the ROWID
     */
    public RowID getRowid() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Gets the attribute value for TXT_STORE_TRANS_TYPE_ID using the alias name txtStoreTransTypeId.
     * @return the TXT_STORE_TRANS_TYPE_ID
     */
    public String gettxtStoreTransTypeId() {
        return (String) getAttributeInternal(TXTSTORETRANSTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_STORE_TRANS_TYPE_ID using the alias name txtStoreTransTypeId.
     * @param value value to set the TXT_STORE_TRANS_TYPE_ID
     */
    public void settxtStoreTransTypeId(String value) {
        setAttributeInternal(TXTSTORETRANSTYPEID, value);
    }

    /**
     * Gets the attribute value for TXT_STORE_ID using the alias name txtStoreId.
     * @return the TXT_STORE_ID
     */
    public String gettxtStoreId() {
        return (String) getAttributeInternal(TXTSTOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_STORE_ID using the alias name txtStoreId.
     * @param value value to set the TXT_STORE_ID
     */
    public void settxtStoreId(String value) {
        setAttributeInternal(TXTSTOREID, value);
    }

    /**
     * Gets the attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @return the TXT_STORE_NAME
     */
    public String gettxtStoreName() {
        return (String) getAttributeInternal(TXTSTORENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_STORE_NAME using the alias name txtStoreName.
     * @param value value to set the TXT_STORE_NAME
     */
    public void settxtStoreName(String value) {
        setAttributeInternal(TXTSTORENAME, value);
    }

    /**
     * Gets the attribute value for ISSUERETSEQ using the alias name Issueretseq.
     * @return the ISSUERETSEQ
     */
    public Integer getIssueretseq() {
        return (Integer) getAttributeInternal(ISSUERETSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for ISSUERETSEQ using the alias name Issueretseq.
     * @param value value to set the ISSUERETSEQ
     */
    public void setIssueretseq(Integer value) {
        setAttributeInternal(ISSUERETSEQ, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrvIssuereturnVO.
     */
    public Row getSrvIssuereturnVO() {
        return (Row) getAttributeInternal(SRVISSUERETURNVO);
    }

    /**
     * Sets the master-detail link SrvIssuereturnVO between this object and <code>value</code>.
     */
    public void setSrvIssuereturnVO(Row value) {
        setAttributeInternal(SRVISSUERETURNVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvIretDetailStoreId.
     */
    public RowSet getAccSrvIretDetailStoreId() {
        return (RowSet) getAttributeInternal(ACCSRVIRETDETAILSTOREID);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccSrvIssueReturnDetailParts.
     */
    public RowSet getAccSrvIssueReturnDetailParts() {
        return (RowSet) getAttributeInternal(ACCSRVISSUERETURNDETAILPARTS);
    }

    public boolean isAttributeUpdateable(int i) {
        if (getSrvIssuereturnVO().getAttribute("Posted").equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    } 
}

