package dgcom.model.vo.srv;

import dgcom.model.vo.srv.common.SrvIssuedetailVO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 23 13:23:52 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvIssuedetailVOImpl extends ViewObjectImpl implements SrvIssuedetailVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvIssuedetailVOImpl() {
    }

    /**
     * Returns the variable value for P_ADF_JOBCARDNO.
     * @return variable value for P_ADF_JOBCARDNO
     */
    public String getP_ADF_JOBCARDNO() {
        return (String) ensureVariableManager().getVariableValue("P_ADF_JOBCARDNO");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_JOBCARDNO.
     * @param value value to bind as P_ADF_JOBCARDNO
     */
    public void setP_ADF_JOBCARDNO(String value) {
        ensureVariableManager().setVariableValue("P_ADF_JOBCARDNO", value);
    }

    public void doCreateNewIssueDetDetRow() {
        //ViewObject vo= this.getRootApplicationModule().findViewObject("SrvJobcardCRUD");
        for (int i = 0; i < 5; i++) {
            this.createRow();
            this.insertRow(this.createRow());
        }

    }   
}

