package dgcom.model.vo.srv;

import dgcom.model.eo.srv.InPartsImpl;
import dgcom.model.eo.srv.SrvIssuedetailImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 23 13:23:52 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvIssuedetailVORowImpl extends ViewRowImpl {


    public static final int ENTITY_SRVISSUEDETAIL = 0;
    public static final int ENTITY_INPARTS = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Issuedetlid,
        IssueId,
        Storeid,
        Partid,
        Reasonid,
        Qty,
        RejectQty,
        Pdqty,
        Retqty,
        Retrejectqty,
        Rate,
        Systemrate,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        RbRejqty,
        Purchrate,
        Partno,
        MastPartid,
        Description,
        txtAmount,
        txtPartName,
        SrvIssuanceVO,
        AccIssuanceJobSwapCIC_0013,
        AccSrvReasonsReasonId,
        AccSysUserStore,
        AccSrvIssueDetailProdIdCIC_0013PartName;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ISSUEDETLID = AttributesEnum.Issuedetlid.index();
    public static final int ISSUEID = AttributesEnum.IssueId.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int PARTID = AttributesEnum.Partid.index();
    public static final int REASONID = AttributesEnum.Reasonid.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int REJECTQTY = AttributesEnum.RejectQty.index();
    public static final int PDQTY = AttributesEnum.Pdqty.index();
    public static final int RETQTY = AttributesEnum.Retqty.index();
    public static final int RETREJECTQTY = AttributesEnum.Retrejectqty.index();
    public static final int RATE = AttributesEnum.Rate.index();
    public static final int SYSTEMRATE = AttributesEnum.Systemrate.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int RBREJQTY = AttributesEnum.RbRejqty.index();
    public static final int PURCHRATE = AttributesEnum.Purchrate.index();
    public static final int PARTNO = AttributesEnum.Partno.index();
    public static final int MASTPARTID = AttributesEnum.MastPartid.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int TXTAMOUNT = AttributesEnum.txtAmount.index();
    public static final int TXTPARTNAME = AttributesEnum.txtPartName.index();
    public static final int SRVISSUANCEVO = AttributesEnum.SrvIssuanceVO.index();
    public static final int ACCISSUANCEJOBSWAPCIC_0013 = AttributesEnum.AccIssuanceJobSwapCIC_0013.index();
    public static final int ACCSRVREASONSREASONID = AttributesEnum.AccSrvReasonsReasonId.index();
    public static final int ACCSYSUSERSTORE = AttributesEnum.AccSysUserStore.index();
    public static final int ACCSRVISSUEDETAILPRODIDCIC_0013PARTNAME =
        AttributesEnum.AccSrvIssueDetailProdIdCIC_0013PartName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvIssuedetailVORowImpl() {
    }

    /**
     * Gets SrvIssuedetail entity object.
     * @return the SrvIssuedetail
     */
    public SrvIssuedetailImpl getSrvIssuedetail() {
        return (SrvIssuedetailImpl) getEntity(ENTITY_SRVISSUEDETAIL);
    }

    /**
     * Gets InParts entity object.
     * @return the InParts
     */
    public InPartsImpl getInParts() {
        return (InPartsImpl) getEntity(ENTITY_INPARTS);
    }

    /**
     * Gets the attribute value for ISSUEDETLID using the alias name Issuedetlid.
     * @return the ISSUEDETLID
     */
    public String getIssuedetlid() {
        return (String) getAttributeInternal(ISSUEDETLID);
    }

    /**
     * Sets <code>value</code> as attribute value for ISSUEDETLID using the alias name Issuedetlid.
     * @param value value to set the ISSUEDETLID
     */
    public void setIssuedetlid(String value) {
        setAttributeInternal(ISSUEDETLID, value);
    }

    /**
     * Gets the attribute value for ISSUE_ID using the alias name IssueId.
     * @return the ISSUE_ID
     */
    public String getIssueId() {
        return (String) getAttributeInternal(ISSUEID);
    }

    /**
     * Sets <code>value</code> as attribute value for ISSUE_ID using the alias name IssueId.
     * @param value value to set the ISSUE_ID
     */
    public void setIssueId(String value) {
        setAttributeInternal(ISSUEID, value);
    }

    /**
     * Gets the attribute value for STOREID using the alias name Storeid.
     * @return the STOREID
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as attribute value for STOREID using the alias name Storeid.
     * @param value value to set the STOREID
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for PARTID using the alias name Partid.
     * @return the PARTID
     */
    public String getPartid() {
        return (String) getAttributeInternal(PARTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTID using the alias name Partid.
     * @param value value to set the PARTID
     */
    public void setPartid(String value) {
        setAttributeInternal(PARTID, value);
    }

    /**
     * Gets the attribute value for REASONID using the alias name Reasonid.
     * @return the REASONID
     */
    public String getReasonid() {
        return (String) getAttributeInternal(REASONID);
    }

    /**
     * Sets <code>value</code> as attribute value for REASONID using the alias name Reasonid.
     * @param value value to set the REASONID
     */
    public void setReasonid(String value) {
        setAttributeInternal(REASONID, value);
    }

    /**
     * Gets the attribute value for QTY using the alias name Qty.
     * @return the QTY
     */
    public BigDecimal getQty() {
        return (BigDecimal) getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as attribute value for QTY using the alias name Qty.
     * @param value value to set the QTY
     */
    public void setQty(BigDecimal value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for REJECT_QTY using the alias name RejectQty.
     * @return the REJECT_QTY
     */
    public BigDecimal getRejectQty() {
        return (BigDecimal) getAttributeInternal(REJECTQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for REJECT_QTY using the alias name RejectQty.
     * @param value value to set the REJECT_QTY
     */
    public void setRejectQty(BigDecimal value) {
        setAttributeInternal(REJECTQTY, value);
    }

    /**
     * Gets the attribute value for PDQTY using the alias name Pdqty.
     * @return the PDQTY
     */
    public BigDecimal getPdqty() {
        return (BigDecimal) getAttributeInternal(PDQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for PDQTY using the alias name Pdqty.
     * @param value value to set the PDQTY
     */
    public void setPdqty(BigDecimal value) {
        setAttributeInternal(PDQTY, value);
    }

    /**
     * Gets the attribute value for RETQTY using the alias name Retqty.
     * @return the RETQTY
     */
    public BigDecimal getRetqty() {
        return (BigDecimal) getAttributeInternal(RETQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for RETQTY using the alias name Retqty.
     * @param value value to set the RETQTY
     */
    public void setRetqty(BigDecimal value) {
        setAttributeInternal(RETQTY, value);
    }

    /**
     * Gets the attribute value for RETREJECTQTY using the alias name Retrejectqty.
     * @return the RETREJECTQTY
     */
    public BigDecimal getRetrejectqty() {
        return (BigDecimal) getAttributeInternal(RETREJECTQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for RETREJECTQTY using the alias name Retrejectqty.
     * @param value value to set the RETREJECTQTY
     */
    public void setRetrejectqty(BigDecimal value) {
        setAttributeInternal(RETREJECTQTY, value);
    }

    /**
     * Gets the attribute value for RATE using the alias name Rate.
     * @return the RATE
     */
    public BigDecimal getRate() {
        return (BigDecimal) getAttributeInternal(RATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RATE using the alias name Rate.
     * @param value value to set the RATE
     */
    public void setRate(BigDecimal value) {
        setAttributeInternal(RATE, value);
    }

    /**
     * Gets the attribute value for SYSTEMRATE using the alias name Systemrate.
     * @return the SYSTEMRATE
     */
    public BigDecimal getSystemrate() {
        return (BigDecimal) getAttributeInternal(SYSTEMRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SYSTEMRATE using the alias name Systemrate.
     * @param value value to set the SYSTEMRATE
     */
    public void setSystemrate(BigDecimal value) {
        setAttributeInternal(SYSTEMRATE, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for RB_REJQTY using the alias name RbRejqty.
     * @return the RB_REJQTY
     */
    public BigDecimal getRbRejqty() {
        return (BigDecimal) getAttributeInternal(RBREJQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for RB_REJQTY using the alias name RbRejqty.
     * @param value value to set the RB_REJQTY
     */
    public void setRbRejqty(BigDecimal value) {
        setAttributeInternal(RBREJQTY, value);
    }

    /**
     * Gets the attribute value for PURCHRATE using the alias name Purchrate.
     * @return the PURCHRATE
     */
    public BigDecimal getPurchrate() {
        return (BigDecimal) getAttributeInternal(PURCHRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PURCHRATE using the alias name Purchrate.
     * @param value value to set the PURCHRATE
     */
    public void setPurchrate(BigDecimal value) {
        setAttributeInternal(PURCHRATE, value);
    }

    /**
     * Gets the attribute value for PARTNO using the alias name Partno.
     * @return the PARTNO
     */
    public String getPartno() {
        return (String) getAttributeInternal(PARTNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTNO using the alias name Partno.
     * @param value value to set the PARTNO
     */
    public void setPartno(String value) {
        setAttributeInternal(PARTNO, value);
    }

    /**
     * Gets the attribute value for PARTID using the alias name MastPartid.
     * @return the PARTID
     */
    public String getMastPartid() {
        return (String) getAttributeInternal(MASTPARTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTID using the alias name MastPartid.
     * @param value value to set the PARTID
     */
    public void setMastPartid(String value) {
        setAttributeInternal(MASTPARTID, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for TXT_AMOUNT using the alias name txtAmount.
     * @return the TXT_AMOUNT
     */
    public BigDecimal gettxtAmount() {
        return (BigDecimal) getAttributeInternal(TXTAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_AMOUNT using the alias name txtAmount.
     * @param value value to set the TXT_AMOUNT
     */
    public void settxtAmount(BigDecimal value) {
        setAttributeInternal(TXTAMOUNT, value);
    }

    /**
     * Gets the attribute value for TXT_PART_NAME using the alias name txtPartName.
     * @return the TXT_PART_NAME
     */
    public String gettxtPartName() {
        return (String) getAttributeInternal(TXTPARTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PART_NAME using the alias name txtPartName.
     * @param value value to set the TXT_PART_NAME
     */
    public void settxtPartName(String value) {
        setAttributeInternal(TXTPARTNAME, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrvIssuanceVO.
     */
    public Row getSrvIssuanceVO() {
        return (Row) getAttributeInternal(SRVISSUANCEVO);
    }

    /**
     * Sets the master-detail link SrvIssuanceVO between this object and <code>value</code>.
     */
    public void setSrvIssuanceVO(Row value) {
        setAttributeInternal(SRVISSUANCEVO, value);
    }


    /**
     * Gets the view accessor <code>RowSet</code> AccIssuanceJobSwapCIC_0013.
     */
    public RowSet getAccIssuanceJobSwapCIC_0013() {
        return (RowSet) getAttributeInternal(ACCISSUANCEJOBSWAPCIC_0013);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvReasonsReasonId.
     */
    public RowSet getAccSrvReasonsReasonId() {
        return (RowSet) getAttributeInternal(ACCSRVREASONSREASONID);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysUserStore.
     */
    public RowSet getAccSysUserStore() {
        return (RowSet) getAttributeInternal(ACCSYSUSERSTORE);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvIssueDetailProdIdCIC_0013PartName.
     */
    public RowSet getAccSrvIssueDetailProdIdCIC_0013PartName() {
        return (RowSet) getAttributeInternal(ACCSRVISSUEDETAILPRODIDCIC_0013PARTNAME);
    }

    public boolean isAttributeUpdateable(int i) {
        if (getSrvIssuanceVO().getAttribute("Posted").equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }    
}

