package dgcom.model.vo.srv;

import dgcom.model.eo.srv.SrvJobsymptomImpl;

import dgcom.model.stand.DigicomClass;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jun 11 11:27:52 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobsymptomVORowImpl extends ViewRowImpl {


    public static final int ENTITY_SRVJOBSYMPTOM = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SymptomId,
        Jobcardno,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        txtSymptomDescription,
        RowID,
        SrvJobcardVO,
        SrvSymptomsVO,
        SrvJobsolutionVO,
        SrvJobqcVO,
        SrvIssuanceVO,
        AccSrvSymptomsSymptomId;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SYMPTOMID = AttributesEnum.SymptomId.index();
    public static final int JOBCARDNO = AttributesEnum.Jobcardno.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int TXTSYMPTOMDESCRIPTION = AttributesEnum.txtSymptomDescription.index();
    public static final int ROWID = AttributesEnum.RowID.index();
    public static final int SRVJOBCARDVO = AttributesEnum.SrvJobcardVO.index();
    public static final int SRVSYMPTOMSVO = AttributesEnum.SrvSymptomsVO.index();
    public static final int SRVJOBSOLUTIONVO = AttributesEnum.SrvJobsolutionVO.index();
    public static final int SRVJOBQCVO = AttributesEnum.SrvJobqcVO.index();
    public static final int SRVISSUANCEVO = AttributesEnum.SrvIssuanceVO.index();
    public static final int ACCSRVSYMPTOMSSYMPTOMID = AttributesEnum.AccSrvSymptomsSymptomId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobsymptomVORowImpl() {
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        if (DigicomClass.doGetModuleId().equals("CIC-0002")) {
            if (getSrvJobcardVO().getAttribute("Posted").equals("Y")) {
                return false;
            }
            return super.isAttributeUpdateable(i);
        } else
            return true;
    }
    /**
     * Gets SrvJobsymptom entity object.
     * @return the SrvJobsymptom
     */
    public SrvJobsymptomImpl getSrvJobsymptom() {
        return (SrvJobsymptomImpl) getEntity(ENTITY_SRVJOBSYMPTOM);
    }

    /**
     * Gets the attribute value for SYMPTOM_ID using the alias name SymptomId.
     * @return the SYMPTOM_ID
     */
    public String getSymptomId() {
        return (String) getAttributeInternal(SYMPTOMID);
    }

    /**
     * Sets <code>value</code> as attribute value for SYMPTOM_ID using the alias name SymptomId.
     * @param value value to set the SYMPTOM_ID
     */
    public void setSymptomId(String value) {
        setAttributeInternal(SYMPTOMID, value);
    }

    /**
     * Gets the attribute value for JOBCARDNO using the alias name Jobcardno.
     * @return the JOBCARDNO
     */
    public String getJobcardno() {
        return (String) getAttributeInternal(JOBCARDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for JOBCARDNO using the alias name Jobcardno.
     * @param value value to set the JOBCARDNO
     */
    public void setJobcardno(String value) {
        setAttributeInternal(JOBCARDNO, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }


    /**
     * Gets the attribute value for the calculated attribute txtSymptomDescription.
     * @return the txtSymptomDescription
     */
    public String gettxtSymptomDescription() {
        return (String) getAttributeInternal(TXTSYMPTOMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute txtSymptomDescription.
     * @param value value to set the  txtSymptomDescription
     */
    public void settxtSymptomDescription(String value) {
        setAttributeInternal(TXTSYMPTOMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name RowID.
     * @return the ROWID
     */
    public RowID getRowID() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrvJobcardVO.
     */
    public Row getSrvJobcardVO() {
        return (Row) getAttributeInternal(SRVJOBCARDVO);
    }

    /**
     * Sets the master-detail link SrvJobcardVO between this object and <code>value</code>.
     */
    public void setSrvJobcardVO(Row value) {
        setAttributeInternal(SRVJOBCARDVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrvSymptomsVO.
     */
    public Row getSrvSymptomsVO() {
        return (Row) getAttributeInternal(SRVSYMPTOMSVO);
    }

    /**
     * Sets the master-detail link SrvSymptomsVO between this object and <code>value</code>.
     */
    public void setSrvSymptomsVO(Row value) {
        setAttributeInternal(SRVSYMPTOMSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrvJobsolutionVO.
     */
    public Row getSrvJobsolutionVO() {
        return (Row) getAttributeInternal(SRVJOBSOLUTIONVO);
    }

    /**
     * Sets the master-detail link SrvJobsolutionVO between this object and <code>value</code>.
     */
    public void setSrvJobsolutionVO(Row value) {
        setAttributeInternal(SRVJOBSOLUTIONVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrvJobqcVO.
     */
    public Row getSrvJobqcVO() {
        return (Row) getAttributeInternal(SRVJOBQCVO);
    }

    /**
     * Sets the master-detail link SrvJobqcVO between this object and <code>value</code>.
     */
    public void setSrvJobqcVO(Row value) {
        setAttributeInternal(SRVJOBQCVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrvIssuanceVO.
     */
    public Row getSrvIssuanceVO() {
        return (Row) getAttributeInternal(SRVISSUANCEVO);
    }

    /**
     * Sets the master-detail link SrvIssuanceVO between this object and <code>value</code>.
     */
    public void setSrvIssuanceVO(Row value) {
        setAttributeInternal(SRVISSUANCEVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvSymptomsSymptomId.
     */
    public RowSet getAccSrvSymptomsSymptomId() {
        return (RowSet) getAttributeInternal(ACCSRVSYMPTOMSSYMPTOMID);
    }
}

