package dgcom.model.vo.srv;

import dgcom.model.eo.srv.SrvJobreturnImpl;
import dgcom.model.stand.DigicomViewRowImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 05 10:25:47 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobreturnVORowImpl extends DigicomViewRowImpl {


    public static final int ENTITY_SRVJOBRETURN = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Jobretid,
        Locationid,
        Tolocationid,
        Jrdate,
        Remarks,
        Posted,
        Postedby,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Status,
        Doctype,
        IsMigrated,
        MigratedDate,
        Jobretidseq,
        SrvJobretdetlVO,
        AccToAllLocations,
        AccSysUserRightsWiseLocation,
        AccSubmitYesNo;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int JOBRETID = AttributesEnum.Jobretid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int TOLOCATIONID = AttributesEnum.Tolocationid.index();
    public static final int JRDATE = AttributesEnum.Jrdate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int DOCTYPE = AttributesEnum.Doctype.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int JOBRETIDSEQ = AttributesEnum.Jobretidseq.index();
    public static final int SRVJOBRETDETLVO = AttributesEnum.SrvJobretdetlVO.index();
    public static final int ACCTOALLLOCATIONS = AttributesEnum.AccToAllLocations.index();
    public static final int ACCSYSUSERRIGHTSWISELOCATION = AttributesEnum.AccSysUserRightsWiseLocation.index();
    public static final int ACCSUBMITYESNO = AttributesEnum.AccSubmitYesNo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobreturnVORowImpl() {
    }

    /**
     * Gets SrvJobreturn entity object.
     * @return the SrvJobreturn
     */
    public SrvJobreturnImpl getSrvJobreturn() {
        return (SrvJobreturnImpl) getEntity(ENTITY_SRVJOBRETURN);
    }

    /**
     * Gets the attribute value for JOBRETID using the alias name Jobretid.
     * @return the JOBRETID
     */
    public String getJobretid() {
        return (String) getAttributeInternal(JOBRETID);
    }

    /**
     * Sets <code>value</code> as attribute value for JOBRETID using the alias name Jobretid.
     * @param value value to set the JOBRETID
     */
    public void setJobretid(String value) {
        setAttributeInternal(JOBRETID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for TOLOCATIONID using the alias name Tolocationid.
     * @return the TOLOCATIONID
     */
    public String getTolocationid() {
        return (String) getAttributeInternal(TOLOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for TOLOCATIONID using the alias name Tolocationid.
     * @param value value to set the TOLOCATIONID
     */
    public void setTolocationid(String value) {
        setAttributeInternal(TOLOCATIONID, value);
    }

    /**
     * Gets the attribute value for JRDATE using the alias name Jrdate.
     * @return the JRDATE
     */
    public Date getJrdate() {
        return (Date) getAttributeInternal(JRDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for JRDATE using the alias name Jrdate.
     * @param value value to set the JRDATE
     */
    public void setJrdate(Date value) {
        setAttributeInternal(JRDATE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for POSTEDBY using the alias name Postedby.
     * @return the POSTEDBY
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTEDBY using the alias name Postedby.
     * @param value value to set the POSTEDBY
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for DOCTYPE using the alias name Doctype.
     * @return the DOCTYPE
     */
    public String getDoctype() {
        return (String) getAttributeInternal(DOCTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCTYPE using the alias name Doctype.
     * @param value value to set the DOCTYPE
     */
    public void setDoctype(String value) {
        setAttributeInternal(DOCTYPE, value);
    }

    /**
     * Gets the attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @return the IS_MIGRATED
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @param value value to set the IS_MIGRATED
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @return the MIGRATED_DATE
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @param value value to set the MIGRATED_DATE
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for JOBRETIDSEQ using the alias name Jobretidseq.
     * @return the JOBRETIDSEQ
     */
    public Integer getJobretidseq() {
        return (Integer) getAttributeInternal(JOBRETIDSEQ);
    }

    /**
     * Sets <code>value</code> as attribute value for JOBRETIDSEQ using the alias name Jobretidseq.
     * @param value value to set the JOBRETIDSEQ
     */
    public void setJobretidseq(Integer value) {
        setAttributeInternal(JOBRETIDSEQ, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrvJobretdetlVO.
     */
    public RowIterator getSrvJobretdetlVO() {
        return (RowIterator) getAttributeInternal(SRVJOBRETDETLVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccToAllLocations.
     */
    public RowSet getAccToAllLocations() {
        return (RowSet) getAttributeInternal(ACCTOALLLOCATIONS);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysUserRightsWiseLocation.
     */
    public RowSet getAccSysUserRightsWiseLocation() {
        return (RowSet) getAttributeInternal(ACCSYSUSERRIGHTSWISELOCATION);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSubmitYesNo.
     */
    public RowSet getAccSubmitYesNo() {
        return (RowSet) getAttributeInternal(ACCSUBMITYESNO);
    }

    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getPosted().equals("Y")) {
            return false;
        }
        else
        return super.isAttributeUpdateable(i);
    }
}

