package dgcom.model.vo.srv;

import dgcom.model.eo.srv.SrvJobqcImpl;
import dgcom.model.stand.DigicomViewRowImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 02 10:27:40 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobqcVORowImpl extends DigicomViewRowImpl {


    public static final int ENTITY_SRVJOBQC = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Qcdocid,
        Locationid,
        Qcpersonid,
        Jobcardno,
        Qcid,
        Qcdate,
        Status,
        Remarks,
        Posted,
        Postedby,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Doctypeid,
        PrevDoctype,
        PrevDocid,
        Jobstatus,
        Reasonid,
        Cdate,
        Mdate,
        IsMigrated,
        MigratedDate,
        txtJobCardLov,
        txtTechnicianName,
        txtImeiNo,
        txtLovName,
        SrvJspartsVO,
        SrvJsprepairVO,
        SrvJobsymptomVO,
        SrvJobfaultVO,
        SrvJobactionVO,
        SrvJobcardVO,
        AccSrvTechnition,
        AccSrvJobQcSrvJobCardNo,
        AccSrvQc,
        AccSrvQcFailBeforeDeliveryJobCardNo,
        AccSrvReasons,
        AccSysUserRightsWiseLocation,
        AccSubmitYesNo,
        AccSrvQcNotOk;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int QCDOCID = AttributesEnum.Qcdocid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int QCPERSONID = AttributesEnum.Qcpersonid.index();
    public static final int JOBCARDNO = AttributesEnum.Jobcardno.index();
    public static final int QCID = AttributesEnum.Qcid.index();
    public static final int QCDATE = AttributesEnum.Qcdate.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int DOCTYPEID = AttributesEnum.Doctypeid.index();
    public static final int PREVDOCTYPE = AttributesEnum.PrevDoctype.index();
    public static final int PREVDOCID = AttributesEnum.PrevDocid.index();
    public static final int JOBSTATUS = AttributesEnum.Jobstatus.index();
    public static final int REASONID = AttributesEnum.Reasonid.index();
    public static final int CDATE = AttributesEnum.Cdate.index();
    public static final int MDATE = AttributesEnum.Mdate.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int TXTJOBCARDLOV = AttributesEnum.txtJobCardLov.index();
    public static final int TXTTECHNICIANNAME = AttributesEnum.txtTechnicianName.index();
    public static final int TXTIMEINO = AttributesEnum.txtImeiNo.index();
    public static final int TXTLOVNAME = AttributesEnum.txtLovName.index();
    public static final int SRVJSPARTSVO = AttributesEnum.SrvJspartsVO.index();
    public static final int SRVJSPREPAIRVO = AttributesEnum.SrvJsprepairVO.index();
    public static final int SRVJOBSYMPTOMVO = AttributesEnum.SrvJobsymptomVO.index();
    public static final int SRVJOBFAULTVO = AttributesEnum.SrvJobfaultVO.index();
    public static final int SRVJOBACTIONVO = AttributesEnum.SrvJobactionVO.index();
    public static final int SRVJOBCARDVO = AttributesEnum.SrvJobcardVO.index();
    public static final int ACCSRVTECHNITION = AttributesEnum.AccSrvTechnition.index();
    public static final int ACCSRVJOBQCSRVJOBCARDNO = AttributesEnum.AccSrvJobQcSrvJobCardNo.index();
    public static final int ACCSRVQC = AttributesEnum.AccSrvQc.index();
    public static final int ACCSRVQCFAILBEFOREDELIVERYJOBCARDNO =
        AttributesEnum.AccSrvQcFailBeforeDeliveryJobCardNo.index();
    public static final int ACCSRVREASONS = AttributesEnum.AccSrvReasons.index();
    public static final int ACCSYSUSERRIGHTSWISELOCATION = AttributesEnum.AccSysUserRightsWiseLocation.index();
    public static final int ACCSUBMITYESNO = AttributesEnum.AccSubmitYesNo.index();
    public static final int ACCSRVQCNOTOK = AttributesEnum.AccSrvQcNotOk.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobqcVORowImpl() {
    }

    /**
     * Gets SrvJobqc entity object.
     * @return the SrvJobqc
     */
    public SrvJobqcImpl getSrvJobqc() {
        return (SrvJobqcImpl) getEntity(ENTITY_SRVJOBQC);
    }

    /**
     * Gets the attribute value for QCDOCID using the alias name Qcdocid.
     * @return the QCDOCID
     */
    public String getQcdocid() {
        return (String) getAttributeInternal(QCDOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for QCDOCID using the alias name Qcdocid.
     * @param value value to set the QCDOCID
     */
    public void setQcdocid(String value) {
        setAttributeInternal(QCDOCID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for QCPERSONID using the alias name Qcpersonid.
     * @return the QCPERSONID
     */
    public String getQcpersonid() {
        return (String) getAttributeInternal(QCPERSONID);
    }

    /**
     * Sets <code>value</code> as attribute value for QCPERSONID using the alias name Qcpersonid.
     * @param value value to set the QCPERSONID
     */
    public void setQcpersonid(String value) {
        setAttributeInternal(QCPERSONID, value);
    }

    /**
     * Gets the attribute value for JOBCARDNO using the alias name Jobcardno.
     * @return the JOBCARDNO
     */
    public String getJobcardno() {
        return (String) getAttributeInternal(JOBCARDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for JOBCARDNO using the alias name Jobcardno.
     * @param value value to set the JOBCARDNO
     */
    public void setJobcardno(String value) {
        setAttributeInternal(JOBCARDNO, value);
    }

    /**
     * Gets the attribute value for QCID using the alias name Qcid.
     * @return the QCID
     */
    public String getQcid() {
        return (String) getAttributeInternal(QCID);
    }

    /**
     * Sets <code>value</code> as attribute value for QCID using the alias name Qcid.
     * @param value value to set the QCID
     */
    public void setQcid(String value) {
        setAttributeInternal(QCID, value);
    }

    /**
     * Gets the attribute value for QCDATE using the alias name Qcdate.
     * @return the QCDATE
     */
    public Date getQcdate() {
        return (Date) getAttributeInternal(QCDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for QCDATE using the alias name Qcdate.
     * @param value value to set the QCDATE
     */
    public void setQcdate(Date value) {
        setAttributeInternal(QCDATE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
        if (value.equals("N")) {
            setQcid("003");
       }
        else
        setQcid(null);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for POSTEDBY using the alias name Postedby.
     * @return the POSTEDBY
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTEDBY using the alias name Postedby.
     * @param value value to set the POSTEDBY
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for DOCTYPEID using the alias name Doctypeid.
     * @return the DOCTYPEID
     */
    public String getDoctypeid() {
        return (String) getAttributeInternal(DOCTYPEID);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCTYPEID using the alias name Doctypeid.
     * @param value value to set the DOCTYPEID
     */
    public void setDoctypeid(String value) {
        setAttributeInternal(DOCTYPEID, value);
    }

    /**
     * Gets the attribute value for PREV_DOCTYPE using the alias name PrevDoctype.
     * @return the PREV_DOCTYPE
     */
    public String getPrevDoctype() {
        return (String) getAttributeInternal(PREVDOCTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for PREV_DOCTYPE using the alias name PrevDoctype.
     * @param value value to set the PREV_DOCTYPE
     */
    public void setPrevDoctype(String value) {
        setAttributeInternal(PREVDOCTYPE, value);
    }

    /**
     * Gets the attribute value for PREV_DOCID using the alias name PrevDocid.
     * @return the PREV_DOCID
     */
    public String getPrevDocid() {
        return (String) getAttributeInternal(PREVDOCID);
    }

    /**
     * Sets <code>value</code> as attribute value for PREV_DOCID using the alias name PrevDocid.
     * @param value value to set the PREV_DOCID
     */
    public void setPrevDocid(String value) {
        setAttributeInternal(PREVDOCID, value);
    }

    /**
     * Gets the attribute value for JOBSTATUS using the alias name Jobstatus.
     * @return the JOBSTATUS
     */
    public String getJobstatus() {
        return (String) getAttributeInternal(JOBSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for JOBSTATUS using the alias name Jobstatus.
     * @param value value to set the JOBSTATUS
     */
    public void setJobstatus(String value) {
        setAttributeInternal(JOBSTATUS, value);
    }

    /**
     * Gets the attribute value for REASONID using the alias name Reasonid.
     * @return the REASONID
     */
    public String getReasonid() {
        return (String) getAttributeInternal(REASONID);
    }

    /**
     * Sets <code>value</code> as attribute value for REASONID using the alias name Reasonid.
     * @param value value to set the REASONID
     */
    public void setReasonid(String value) {
        setAttributeInternal(REASONID, value);
    }

    /**
     * Gets the attribute value for CDATE using the alias name Cdate.
     * @return the CDATE
     */
    public Date getCdate() {
        return (Date) getAttributeInternal(CDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CDATE using the alias name Cdate.
     * @param value value to set the CDATE
     */
    public void setCdate(Date value) {
        setAttributeInternal(CDATE, value);
    }

    /**
     * Gets the attribute value for MDATE using the alias name Mdate.
     * @return the MDATE
     */
    public Date getMdate() {
        return (Date) getAttributeInternal(MDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MDATE using the alias name Mdate.
     * @param value value to set the MDATE
     */
    public void setMdate(Date value) {
        setAttributeInternal(MDATE, value);
    }

    /**
     * Gets the attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @return the IS_MIGRATED
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @param value value to set the IS_MIGRATED
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @return the MIGRATED_DATE
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @param value value to set the MIGRATED_DATE
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtJobCardLov.
     * @return the txtJobCardLov
     */
    public String gettxtJobCardLov() {
        return (String) getAttributeInternal(TXTJOBCARDLOV);
    }


    /**
     * Gets the attribute value for TXT_TECHNICIAN_NAME using the alias name txtTechnicianName.
     * @return the TXT_TECHNICIAN_NAME
     */
    public String gettxtTechnicianName() {
        return (String) getAttributeInternal(TXTTECHNICIANNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_TECHNICIAN_NAME using the alias name txtTechnicianName.
     * @param value value to set the TXT_TECHNICIAN_NAME
     */
    public void settxtTechnicianName(String value) {
        setAttributeInternal(TXTTECHNICIANNAME, value);
    }

    /**
     * Gets the attribute value for TXT_IMEI_NO using the alias name txtImeiNo.
     * @return the TXT_IMEI_NO
     */
    public String gettxtImeiNo() {
        return (String) getAttributeInternal(TXTIMEINO);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_IMEI_NO using the alias name txtImeiNo.
     * @param value value to set the TXT_IMEI_NO
     */
    public void settxtImeiNo(String value) {
        setAttributeInternal(TXTIMEINO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute txtLovName.
     * @return the txtLovName
     */
    public String gettxtLovName() {
        return (String) getAttributeInternal(TXTLOVNAME);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrvJspartsVO.
     */
    public RowIterator getSrvJspartsVO() {
        return (RowIterator) getAttributeInternal(SRVJSPARTSVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrvJsprepairVO.
     */
    public RowIterator getSrvJsprepairVO() {
        return (RowIterator) getAttributeInternal(SRVJSPREPAIRVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrvJobsymptomVO.
     */
    public RowIterator getSrvJobsymptomVO() {
        return (RowIterator) getAttributeInternal(SRVJOBSYMPTOMVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrvJobfaultVO.
     */
    public RowIterator getSrvJobfaultVO() {
        return (RowIterator) getAttributeInternal(SRVJOBFAULTVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrvJobactionVO.
     */
    public RowIterator getSrvJobactionVO() {
        return (RowIterator) getAttributeInternal(SRVJOBACTIONVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrvJobcardVO.
     */
    public Row getSrvJobcardVO() {
        return (Row) getAttributeInternal(SRVJOBCARDVO);
    }

    /**
     * Sets the master-detail link SrvJobcardVO between this object and <code>value</code>.
     */
    public void setSrvJobcardVO(Row value) {
        setAttributeInternal(SRVJOBCARDVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvTechnition.
     */
    public RowSet getAccSrvTechnition() {
        return (RowSet) getAttributeInternal(ACCSRVTECHNITION);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvJobQcSrvJobCardNo.
     */
    public RowSet getAccSrvJobQcSrvJobCardNo() {
        return (RowSet) getAttributeInternal(ACCSRVJOBQCSRVJOBCARDNO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvQc.
     */
    public RowSet getAccSrvQc() {
        return (RowSet) getAttributeInternal(ACCSRVQC);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvQcFailBeforeDeliveryJobCardNo.
     */
    public RowSet getAccSrvQcFailBeforeDeliveryJobCardNo() {
        return (RowSet) getAttributeInternal(ACCSRVQCFAILBEFOREDELIVERYJOBCARDNO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvReasons.
     */
    public RowSet getAccSrvReasons() {
        return (RowSet) getAttributeInternal(ACCSRVREASONS);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysUserRightsWiseLocation.
     */
    public RowSet getAccSysUserRightsWiseLocation() {
        return (RowSet) getAttributeInternal(ACCSYSUSERRIGHTSWISELOCATION);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSubmitYesNo.
     */
    public RowSet getAccSubmitYesNo() {
        return (RowSet) getAttributeInternal(ACCSUBMITYESNO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSrvQcNotOk.
     */
    public RowSet getAccSrvQcNotOk() {
        return (RowSet) getAttributeInternal(ACCSRVQCNOTOK);
    }

    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getPosted().equals("Y")) {
            return false;
        }
        else
        return super.isAttributeUpdateable(i);
    }
}

