package dgcom.model.vo.srv;

import dgcom.model.eo.srv.SrvJobassignImpl;

import dgcom.model.stand.DigicomViewRowImpl;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 23 09:33:40 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobassignVORowImpl extends DigicomViewRowImpl {


    public static final int ENTITY_SRVJOBASSIGN = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Assignid,
        Locationid,
        Technicianid,
        Assdate,
        Remarks,
        Posted,
        Postedby,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        IsMigrated,
        MigratedDate,
        txtTechnicianName,
        SrvJobassdetlVO,
        AccTechnitionJobAssignTechnitionID,
        AccSysUserRightsWiseLocation,
        AccSubmitYesNo;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ASSIGNID = AttributesEnum.Assignid.index();
    public static final int LOCATIONID = AttributesEnum.Locationid.index();
    public static final int TECHNICIANID = AttributesEnum.Technicianid.index();
    public static final int ASSDATE = AttributesEnum.Assdate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int POSTED = AttributesEnum.Posted.index();
    public static final int POSTEDBY = AttributesEnum.Postedby.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int ISMIGRATED = AttributesEnum.IsMigrated.index();
    public static final int MIGRATEDDATE = AttributesEnum.MigratedDate.index();
    public static final int TXTTECHNICIANNAME = AttributesEnum.txtTechnicianName.index();
    public static final int SRVJOBASSDETLVO = AttributesEnum.SrvJobassdetlVO.index();
    public static final int ACCTECHNITIONJOBASSIGNTECHNITIONID =
        AttributesEnum.AccTechnitionJobAssignTechnitionID.index();
    public static final int ACCSYSUSERRIGHTSWISELOCATION = AttributesEnum.AccSysUserRightsWiseLocation.index();
    public static final int ACCSUBMITYESNO = AttributesEnum.AccSubmitYesNo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobassignVORowImpl() {
    }

    /**
     * Gets SrvJobassign entity object.
     * @return the SrvJobassign
     */
    public SrvJobassignImpl getSrvJobassign() {
        return (SrvJobassignImpl) getEntity(ENTITY_SRVJOBASSIGN);
    }

    /**
     * Gets the attribute value for ASSIGNID using the alias name Assignid.
     * @return the ASSIGNID
     */
    public String getAssignid() {
        return (String) getAttributeInternal(ASSIGNID);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSIGNID using the alias name Assignid.
     * @param value value to set the ASSIGNID
     */
    public void setAssignid(String value) {
        setAttributeInternal(ASSIGNID, value);
    }

    /**
     * Gets the attribute value for LOCATIONID using the alias name Locationid.
     * @return the LOCATIONID
     */
    public String getLocationid() {
        return (String) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATIONID using the alias name Locationid.
     * @param value value to set the LOCATIONID
     */
    public void setLocationid(String value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for TECHNICIANID using the alias name Technicianid.
     * @return the TECHNICIANID
     */
    public String getTechnicianid() {
        return (String) getAttributeInternal(TECHNICIANID);
    }

    /**
     * Sets <code>value</code> as attribute value for TECHNICIANID using the alias name Technicianid.
     * @param value value to set the TECHNICIANID
     */
    public void setTechnicianid(String value) {
        setAttributeInternal(TECHNICIANID, value);
    }

    /**
     * Gets the attribute value for ASSDATE using the alias name Assdate.
     * @return the ASSDATE
     */
    public Date getAssdate() {
        return (Date) getAttributeInternal(ASSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ASSDATE using the alias name Assdate.
     * @param value value to set the ASSDATE
     */
    public void setAssdate(Date value) {
        setAttributeInternal(ASSDATE, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for POSTED using the alias name Posted.
     * @return the POSTED
     */
    public String getPosted() {
        return (String) getAttributeInternal(POSTED);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTED using the alias name Posted.
     * @param value value to set the POSTED
     */
    public void setPosted(String value) {
        setAttributeInternal(POSTED, value);
    }

    /**
     * Gets the attribute value for POSTEDBY using the alias name Postedby.
     * @return the POSTEDBY
     */
    public String getPostedby() {
        return (String) getAttributeInternal(POSTEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for POSTEDBY using the alias name Postedby.
     * @param value value to set the POSTEDBY
     */
    public void setPostedby(String value) {
        setAttributeInternal(POSTEDBY, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @return the IS_MIGRATED
     */
    public String getIsMigrated() {
        return (String) getAttributeInternal(ISMIGRATED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_MIGRATED using the alias name IsMigrated.
     * @param value value to set the IS_MIGRATED
     */
    public void setIsMigrated(String value) {
        setAttributeInternal(ISMIGRATED, value);
    }

    /**
     * Gets the attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @return the MIGRATED_DATE
     */
    public Date getMigratedDate() {
        return (Date) getAttributeInternal(MIGRATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MIGRATED_DATE using the alias name MigratedDate.
     * @param value value to set the MIGRATED_DATE
     */
    public void setMigratedDate(Date value) {
        setAttributeInternal(MIGRATEDDATE, value);
    }

    /**
     * Gets the attribute value for TXT_TECHNICIAN_NAME using the alias name txtTechnicianName.
     * @return the TXT_TECHNICIAN_NAME
     */
    public String gettxtTechnicianName() {
        return (String) getAttributeInternal(TXTTECHNICIANNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_TECHNICIAN_NAME using the alias name txtTechnicianName.
     * @param value value to set the TXT_TECHNICIAN_NAME
     */
    public void settxtTechnicianName(String value) {
        setAttributeInternal(TXTTECHNICIANNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link SrvJobassdetlVO.
     */
    public RowIterator getSrvJobassdetlVO() {
        return (RowIterator) getAttributeInternal(SRVJOBASSDETLVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccTechnitionJobAssignTechnitionID.
     */
    public RowSet getAccTechnitionJobAssignTechnitionID() {
        return (RowSet) getAttributeInternal(ACCTECHNITIONJOBASSIGNTECHNITIONID);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysUserRightsWiseLocation.
     */
    public RowSet getAccSysUserRightsWiseLocation() {
        return (RowSet) getAttributeInternal(ACCSYSUSERRIGHTSWISELOCATION);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSubmitYesNo.
     */
    public RowSet getAccSubmitYesNo() {
        return (RowSet) getAttributeInternal(ACCSUBMITYESNO);
    }

    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getPosted().equals("Y")) {
            return false;
        }
        else
        return super.isAttributeUpdateable(i);
    }
}

