package dgcom.model.vo.srv;

import dgcom.model.stand.DigicomViewObjectImpl;
import dgcom.model.vo.srv.common.SrvJobsolutionVO;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import oracle.jbo.JboException;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 28 13:03:30 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobsolutionVOImpl extends DigicomViewObjectImpl implements SrvJobsolutionVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobsolutionVOImpl() {
    }
    public void doSubmitJobSolutions() {
        
        CallableStatement cs=this.getDBTransaction().createCallableStatement("begin ?:=PKG_SERVICE.FUNC_SRV_JOB_SOLUTION_SUBMIT('"+this.getCurrentRow().getAttribute("JsolutionId")+"'); END;", 1);
        System.out.println("begin ?:=PKG_SERVICE.FUNC_SRV_JOB_SOLUTION_SUBMIT('"+this.getCurrentRow().getAttribute("JsolutionId")+"'); END;");
        try {
            cs.registerOutParameter(1, Types.VARCHAR);
            cs.executeUpdate();
            if (!cs.getString(1).equals("Y")) {
               this.getCurrentRow().setAttribute("Posted", "N");
               this.getDBTransaction().commit();
                throw new JboException("Unable to supervise due to "+cs.getString(1));
               
           }
            this.getDBTransaction().commit();
        } catch (SQLException e) {
            this.getCurrentRow().setAttribute("Posted", "N");
            this.getDBTransaction().commit();
            System.out.println(e.getMessage()+ "this is message");
            throw new JboException("Unable to supervise ");
        }
    }

    public void doCreateNewJobSolRow() {
        Row r=this.createRow();
        r.setNewRowState(Row.STATUS_NEW);
        this.insertRow(r);
    } 

    
}

