package dgcom.model.vo.srv;

import dgcom.model.stand.DigicomViewObjectImpl;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 14 14:50:09 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobtypesVOImpl extends DigicomViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobtypesVOImpl() {
    }
}

