package dgcom.model.vo.srv;

import dgcom.model.stand.DigicomViewObjectImpl;
import dgcom.model.vo.srv.common.SrvLogdetlVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 25 12:29:08 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvLogdetlVOImpl extends DigicomViewObjectImpl implements SrvLogdetlVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvLogdetlVOImpl() {
    }
    public void doCreateNewLogisticDetRow() {
        //ViewObject vo= this.getRootApplicationModule().findViewObject("SrvJobcardCRUD");

        /*if (!DigicomClass.doGetModuleId().equals("CIC-0082")) */{
            for (int i = 0; i < 0; i++) {
                this.createRow();
                this.insertRow(this.createRow());
            }
        }

    }     
    
}

