package dgcom.model.vo.srv;

import dgcom.model.stand.DigicomViewObjectImpl;
import dgcom.model.vo.srv.common.SrvPsdetlVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 25 13:33:20 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvPsdetlVOImpl extends DigicomViewObjectImpl implements SrvPsdetlVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvPsdetlVOImpl() {
    }
    public void doCreateNewPartSaleDetRow() {
        //ViewObject vo= this.getRootApplicationModule().findViewObject("SrvJobcardCRUD");
        for (int i = 0; i < 5; i++) {
            this.createRow();
            this.insertRow(this.createRow());
        }

    }     
}

