package dgcom.model.vo.srv;

import dgcom.model.eo.srv.SrvRfwdetlImpl;
import dgcom.model.stand.DigicomViewRowImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Mar 08 10:27:25 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvRfwdetlVORowImpl extends DigicomViewRowImpl {
    public static final int ENTITY_SRVRFWDETL = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Rfwid,
        Jobcardno,
        Startdate,
        Expdate,
        NewItemid,
        ImeiNo,
        Createdby,
        CreatedDate,
        Modifiedby,
        ModifiedDate,
        Itemid,
        Rowid,
        txtNewItemIdDesc,
        txtItemidDesc,
        SrvRfwarrantyVO,
        InItemsVO,
        InItemsVO1,
        SrvJobcardVO,
        AccInItems,
        AccInItemsNewItem;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int RFWID = AttributesEnum.Rfwid.index();
    public static final int JOBCARDNO = AttributesEnum.Jobcardno.index();
    public static final int STARTDATE = AttributesEnum.Startdate.index();
    public static final int EXPDATE = AttributesEnum.Expdate.index();
    public static final int NEWITEMID = AttributesEnum.NewItemid.index();
    public static final int IMEINO = AttributesEnum.ImeiNo.index();
    public static final int CREATEDBY = AttributesEnum.Createdby.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int MODIFIEDBY = AttributesEnum.Modifiedby.index();
    public static final int MODIFIEDDATE = AttributesEnum.ModifiedDate.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int ROWID = AttributesEnum.Rowid.index();
    public static final int TXTNEWITEMIDDESC = AttributesEnum.txtNewItemIdDesc.index();
    public static final int TXTITEMIDDESC = AttributesEnum.txtItemidDesc.index();
    public static final int SRVRFWARRANTYVO = AttributesEnum.SrvRfwarrantyVO.index();
    public static final int INITEMSVO = AttributesEnum.InItemsVO.index();
    public static final int INITEMSVO1 = AttributesEnum.InItemsVO1.index();
    public static final int SRVJOBCARDVO = AttributesEnum.SrvJobcardVO.index();
    public static final int ACCINITEMS = AttributesEnum.AccInItems.index();
    public static final int ACCINITEMSNEWITEM = AttributesEnum.AccInItemsNewItem.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SrvRfwdetlVORowImpl() {
    }

    /**
     * Gets SrvRfwdetl entity object.
     * @return the SrvRfwdetl
     */
    public SrvRfwdetlImpl getSrvRfwdetl() {
        return (SrvRfwdetlImpl) getEntity(ENTITY_SRVRFWDETL);
    }

    /**
     * Gets the attribute value for RFWID using the alias name Rfwid.
     * @return the RFWID
     */
    public String getRfwid() {
        return (String) getAttributeInternal(RFWID);
    }

    /**
     * Sets <code>value</code> as attribute value for RFWID using the alias name Rfwid.
     * @param value value to set the RFWID
     */
    public void setRfwid(String value) {
        setAttributeInternal(RFWID, value);
    }

    /**
     * Gets the attribute value for JOBCARDNO using the alias name Jobcardno.
     * @return the JOBCARDNO
     */
    public String getJobcardno() {
        return (String) getAttributeInternal(JOBCARDNO);
    }

    /**
     * Sets <code>value</code> as attribute value for JOBCARDNO using the alias name Jobcardno.
     * @param value value to set the JOBCARDNO
     */
    public void setJobcardno(String value) {
        setAttributeInternal(JOBCARDNO, value);
    }

    /**
     * Gets the attribute value for STARTDATE using the alias name Startdate.
     * @return the STARTDATE
     */
    public Date getStartdate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for STARTDATE using the alias name Startdate.
     * @param value value to set the STARTDATE
     */
    public void setStartdate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for EXPDATE using the alias name Expdate.
     * @return the EXPDATE
     */
    public Date getExpdate() {
        return (Date) getAttributeInternal(EXPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPDATE using the alias name Expdate.
     * @param value value to set the EXPDATE
     */
    public void setExpdate(Date value) {
        setAttributeInternal(EXPDATE, value);
    }

    /**
     * Gets the attribute value for NEW_ITEMID using the alias name NewItemid.
     * @return the NEW_ITEMID
     */
    public String getNewItemid() {
        return (String) getAttributeInternal(NEWITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for NEW_ITEMID using the alias name NewItemid.
     * @param value value to set the NEW_ITEMID
     */
    public void setNewItemid(String value) {
        setAttributeInternal(NEWITEMID, value);
    }

    /**
     * Gets the attribute value for IMEI_NO using the alias name ImeiNo.
     * @return the IMEI_NO
     */
    public Long getImeiNo() {
        return (Long) getAttributeInternal(IMEINO);
    }

    /**
     * Sets <code>value</code> as attribute value for IMEI_NO using the alias name ImeiNo.
     * @param value value to set the IMEI_NO
     */
    public void setImeiNo(Long value) {
        setAttributeInternal(IMEINO, value);
    }

    /**
     * Gets the attribute value for CREATEDBY using the alias name Createdby.
     * @return the CREATEDBY
     */
    public String getCreatedby() {
        return (String) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATEDBY using the alias name Createdby.
     * @param value value to set the CREATEDBY
     */
    public void setCreatedby(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @return the MODIFIEDBY
     */
    public String getModifiedby() {
        return (String) getAttributeInternal(MODIFIEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIEDBY using the alias name Modifiedby.
     * @param value value to set the MODIFIEDBY
     */
    public void setModifiedby(String value) {
        setAttributeInternal(MODIFIEDBY, value);
    }

    /**
     * Gets the attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @return the MODIFIED_DATE
     */
    public Date getModifiedDate() {
        return (Date) getAttributeInternal(MODIFIEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFIED_DATE using the alias name ModifiedDate.
     * @param value value to set the MODIFIED_DATE
     */
    public void setModifiedDate(Date value) {
        setAttributeInternal(MODIFIEDDATE, value);
    }

    /**
     * Gets the attribute value for ITEMID using the alias name Itemid.
     * @return the ITEMID
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEMID using the alias name Itemid.
     * @param value value to set the ITEMID
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ROWID using the alias name Rowid.
     * @return the ROWID
     */
    public RowID getRowid() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Gets the attribute value for TXT_NEW_ITEM_ID_DESC using the alias name txtNewItemIdDesc.
     * @return the TXT_NEW_ITEM_ID_DESC
     */
    public String gettxtNewItemIdDesc() {
        return (String) getAttributeInternal(TXTNEWITEMIDDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_NEW_ITEM_ID_DESC using the alias name txtNewItemIdDesc.
     * @param value value to set the TXT_NEW_ITEM_ID_DESC
     */
    public void settxtNewItemIdDesc(String value) {
        setAttributeInternal(TXTNEWITEMIDDESC, value);
    }

    /**
     * Gets the attribute value for TXT_ITEMID_DESC using the alias name txtItemidDesc.
     * @return the TXT_ITEMID_DESC
     */
    public String gettxtItemidDesc() {
        return (String) getAttributeInternal(TXTITEMIDDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_ITEMID_DESC using the alias name txtItemidDesc.
     * @param value value to set the TXT_ITEMID_DESC
     */
    public void settxtItemidDesc(String value) {
        setAttributeInternal(TXTITEMIDDESC, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrvRfwarrantyVO.
     */
    public Row getSrvRfwarrantyVO() {
        return (Row) getAttributeInternal(SRVRFWARRANTYVO);
    }

    /**
     * Sets the master-detail link SrvRfwarrantyVO between this object and <code>value</code>.
     */
    public void setSrvRfwarrantyVO(Row value) {
        setAttributeInternal(SRVRFWARRANTYVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InItemsVO.
     */
    public Row getInItemsVO() {
        return (Row) getAttributeInternal(INITEMSVO);
    }

    /**
     * Sets the master-detail link InItemsVO between this object and <code>value</code>.
     */
    public void setInItemsVO(Row value) {
        setAttributeInternal(INITEMSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InItemsVO1.
     */
    public Row getInItemsVO1() {
        return (Row) getAttributeInternal(INITEMSVO1);
    }

    /**
     * Sets the master-detail link InItemsVO1 between this object and <code>value</code>.
     */
    public void setInItemsVO1(Row value) {
        setAttributeInternal(INITEMSVO1, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link SrvJobcardVO.
     */
    public Row getSrvJobcardVO() {
        return (Row) getAttributeInternal(SRVJOBCARDVO);
    }

    /**
     * Sets the master-detail link SrvJobcardVO between this object and <code>value</code>.
     */
    public void setSrvJobcardVO(Row value) {
        setAttributeInternal(SRVJOBCARDVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInItems.
     */
    public RowSet getAccInItems() {
        return (RowSet) getAttributeInternal(ACCINITEMS);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInItemsNewItem.
     */
    public RowSet getAccInItemsNewItem() {
        return (RowSet) getAttributeInternal(ACCINITEMSNEWITEM);
    }

    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getSrvRfwarrantyVO().getAttribute("Posted").equals("Y")) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

