package dgcom.model.vo.srv;

import dgcom.model.stand.DigicomViewObjectImpl;

import dgcom.model.vo.srv.common.SrvSetReplacementVO;

import java.sql.CallableStatement;
import java.sql.SQLException;
import java.sql.Types;

import oracle.jbo.JboException;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jul 23 09:37:41 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvSetReplacementVOImpl extends DigicomViewObjectImpl implements SrvSetReplacementVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvSetReplacementVOImpl() {
    }

    /**
     * Returns the variable value for P_ADF_JOBCARD_NO.
     * @return variable value for P_ADF_JOBCARD_NO
     */
    public String getP_ADF_JOBCARD_NO() {
        return (String) ensureVariableManager().getVariableValue("P_ADF_JOBCARD_NO");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_JOBCARD_NO.
     * @param value value to bind as P_ADF_JOBCARD_NO
     */
    public void setP_ADF_JOBCARD_NO(String value) {
        ensureVariableManager().setVariableValue("P_ADF_JOBCARD_NO", value);
    }
    public void doSubmitSetReplacement() {
        
        CallableStatement cs=this.getDBTransaction().createCallableStatement("begin ?:=PKG_SERVICE.FUNC_SRV_SET_REPLACE_SUBMIT('"+this.getCurrentRow().getAttribute("SrId")+"'); END;", 1);
        try {
            cs.registerOutParameter(1, Types.VARCHAR);
            cs.executeUpdate();
            if (!cs.getString(1).equals("Y")) {
               this.getCurrentRow().setAttribute("Posted", "N");
               this.getDBTransaction().commit();
                throw new JboException("Unable to supervise due to "+cs.getString(1));
               
           }
            this.getDBTransaction().commit();
        } catch (SQLException e) {
            this.getCurrentRow().setAttribute("Posted", "N");
            this.getDBTransaction().commit();
            System.out.println(e.getMessage()+ "this is message");
            throw new JboException("Unable to supervise ");
        }
    }
}

