package dgcom.model.vo.srv;

import dgcom.model.stand.DigicomViewObjectImpl;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 23 09:36:52 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvTechnicianVOImpl extends DigicomViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvTechnicianVOImpl() {
    }

    /**
     * Returns the variable value for P_ADF_LOCATIONID.
     * @return variable value for P_ADF_LOCATIONID
     */
    public String getP_ADF_LOCATIONID() {
        return (String) ensureVariableManager().getVariableValue("P_ADF_LOCATIONID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_LOCATIONID.
     * @param value value to bind as P_ADF_LOCATIONID
     */
    public void setP_ADF_LOCATIONID(String value) {
        ensureVariableManager().setVariableValue("P_ADF_LOCATIONID", value);
    }
}

