package dgcom.model.eo.inv;

import java.math.BigDecimal;
import java.math.BigInteger;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.RowID;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 15 11:21:24 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemImeiInfoImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Imei,
        Storeid,
        IsAvailable,
        BoxNo,
        Itemid,
        Productid,
        Customerid,
        RestrictImei,
        ForceAllow,
        AllowSo,
        AllowSr,
        StopCustomer,
        PreviousStore,
        IsScan,
        IsJobCard,
        Incentive,
        IncentiveMsg,
        SourceId,
        TotalImei,
        ActiveDate,
        SaleDate,
        IncDebitAmount,
        SprDebitAmount,
        SerialNo,
        IncentiveCancel,
        IsCounterDead,
        IncCanDoctype,
        IncCanDocid,
        StartDate,
        ExpDate,
        Rowid,
        txtBrandid,
        SrvJobcard,
        InItems;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IMEI = AttributesEnum.Imei.index();
    public static final int STOREID = AttributesEnum.Storeid.index();
    public static final int ISAVAILABLE = AttributesEnum.IsAvailable.index();
    public static final int BOXNO = AttributesEnum.BoxNo.index();
    public static final int ITEMID = AttributesEnum.Itemid.index();
    public static final int PRODUCTID = AttributesEnum.Productid.index();
    public static final int CUSTOMERID = AttributesEnum.Customerid.index();
    public static final int RESTRICTIMEI = AttributesEnum.RestrictImei.index();
    public static final int FORCEALLOW = AttributesEnum.ForceAllow.index();
    public static final int ALLOWSO = AttributesEnum.AllowSo.index();
    public static final int ALLOWSR = AttributesEnum.AllowSr.index();
    public static final int STOPCUSTOMER = AttributesEnum.StopCustomer.index();
    public static final int PREVIOUSSTORE = AttributesEnum.PreviousStore.index();
    public static final int ISSCAN = AttributesEnum.IsScan.index();
    public static final int ISJOBCARD = AttributesEnum.IsJobCard.index();
    public static final int INCENTIVE = AttributesEnum.Incentive.index();
    public static final int INCENTIVEMSG = AttributesEnum.IncentiveMsg.index();
    public static final int SOURCEID = AttributesEnum.SourceId.index();
    public static final int TOTALIMEI = AttributesEnum.TotalImei.index();
    public static final int ACTIVEDATE = AttributesEnum.ActiveDate.index();
    public static final int SALEDATE = AttributesEnum.SaleDate.index();
    public static final int INCDEBITAMOUNT = AttributesEnum.IncDebitAmount.index();
    public static final int SPRDEBITAMOUNT = AttributesEnum.SprDebitAmount.index();
    public static final int SERIALNO = AttributesEnum.SerialNo.index();
    public static final int INCENTIVECANCEL = AttributesEnum.IncentiveCancel.index();
    public static final int ISCOUNTERDEAD = AttributesEnum.IsCounterDead.index();
    public static final int INCCANDOCTYPE = AttributesEnum.IncCanDoctype.index();
    public static final int INCCANDOCID = AttributesEnum.IncCanDocid.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int EXPDATE = AttributesEnum.ExpDate.index();
    public static final int ROWID = AttributesEnum.Rowid.index();
    public static final int TXTBRANDID = AttributesEnum.txtBrandid.index();
    public static final int SRVJOBCARD = AttributesEnum.SrvJobcard.index();
    public static final int INITEMS = AttributesEnum.InItems.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ItemImeiInfoImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("dgcom.model.eo.inv.ItemImeiInfo");
    }


    /**
     * Gets the attribute value for Imei, using the alias name Imei.
     * @return the value of Imei
     */
    public BigInteger getImei() {
        return (BigInteger) getAttributeInternal(IMEI);
    }

    /**
     * Sets <code>value</code> as the attribute value for Imei.
     * @param value value to set the Imei
     */
    public void setImei(BigInteger value) {
        setAttributeInternal(IMEI, value);
    }

    /**
     * Gets the attribute value for Storeid, using the alias name Storeid.
     * @return the value of Storeid
     */
    public String getStoreid() {
        return (String) getAttributeInternal(STOREID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Storeid.
     * @param value value to set the Storeid
     */
    public void setStoreid(String value) {
        setAttributeInternal(STOREID, value);
    }

    /**
     * Gets the attribute value for IsAvailable, using the alias name IsAvailable.
     * @return the value of IsAvailable
     */
    public String getIsAvailable() {
        return (String) getAttributeInternal(ISAVAILABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsAvailable.
     * @param value value to set the IsAvailable
     */
    public void setIsAvailable(String value) {
        setAttributeInternal(ISAVAILABLE, value);
    }

    /**
     * Gets the attribute value for BoxNo, using the alias name BoxNo.
     * @return the value of BoxNo
     */
    public String getBoxNo() {
        return (String) getAttributeInternal(BOXNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for BoxNo.
     * @param value value to set the BoxNo
     */
    public void setBoxNo(String value) {
        setAttributeInternal(BOXNO, value);
    }

    /**
     * Gets the attribute value for Itemid, using the alias name Itemid.
     * @return the value of Itemid
     */
    public String getItemid() {
        return (String) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Itemid.
     * @param value value to set the Itemid
     */
    public void setItemid(String value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for Productid, using the alias name Productid.
     * @return the value of Productid
     */
    public String getProductid() {
        return (String) getAttributeInternal(PRODUCTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Productid.
     * @param value value to set the Productid
     */
    public void setProductid(String value) {
        setAttributeInternal(PRODUCTID, value);
    }

    /**
     * Gets the attribute value for Customerid, using the alias name Customerid.
     * @return the value of Customerid
     */
    public String getCustomerid() {
        return (String) getAttributeInternal(CUSTOMERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Customerid.
     * @param value value to set the Customerid
     */
    public void setCustomerid(String value) {
        setAttributeInternal(CUSTOMERID, value);
    }

    /**
     * Gets the attribute value for RestrictImei, using the alias name RestrictImei.
     * @return the value of RestrictImei
     */
    public String getRestrictImei() {
        return (String) getAttributeInternal(RESTRICTIMEI);
    }

    /**
     * Sets <code>value</code> as the attribute value for RestrictImei.
     * @param value value to set the RestrictImei
     */
    public void setRestrictImei(String value) {
        setAttributeInternal(RESTRICTIMEI, value);
    }

    /**
     * Gets the attribute value for ForceAllow, using the alias name ForceAllow.
     * @return the value of ForceAllow
     */
    public String getForceAllow() {
        return (String) getAttributeInternal(FORCEALLOW);
    }

    /**
     * Sets <code>value</code> as the attribute value for ForceAllow.
     * @param value value to set the ForceAllow
     */
    public void setForceAllow(String value) {
        setAttributeInternal(FORCEALLOW, value);
    }

    /**
     * Gets the attribute value for AllowSo, using the alias name AllowSo.
     * @return the value of AllowSo
     */
    public String getAllowSo() {
        return (String) getAttributeInternal(ALLOWSO);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowSo.
     * @param value value to set the AllowSo
     */
    public void setAllowSo(String value) {
        setAttributeInternal(ALLOWSO, value);
    }

    /**
     * Gets the attribute value for AllowSr, using the alias name AllowSr.
     * @return the value of AllowSr
     */
    public String getAllowSr() {
        return (String) getAttributeInternal(ALLOWSR);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowSr.
     * @param value value to set the AllowSr
     */
    public void setAllowSr(String value) {
        setAttributeInternal(ALLOWSR, value);
    }

    /**
     * Gets the attribute value for StopCustomer, using the alias name StopCustomer.
     * @return the value of StopCustomer
     */
    public String getStopCustomer() {
        return (String) getAttributeInternal(STOPCUSTOMER);
    }

    /**
     * Sets <code>value</code> as the attribute value for StopCustomer.
     * @param value value to set the StopCustomer
     */
    public void setStopCustomer(String value) {
        setAttributeInternal(STOPCUSTOMER, value);
    }

    /**
     * Gets the attribute value for PreviousStore, using the alias name PreviousStore.
     * @return the value of PreviousStore
     */
    public String getPreviousStore() {
        return (String) getAttributeInternal(PREVIOUSSTORE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreviousStore.
     * @param value value to set the PreviousStore
     */
    public void setPreviousStore(String value) {
        setAttributeInternal(PREVIOUSSTORE, value);
    }

    /**
     * Gets the attribute value for IsScan, using the alias name IsScan.
     * @return the value of IsScan
     */
    public String getIsScan() {
        return (String) getAttributeInternal(ISSCAN);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsScan.
     * @param value value to set the IsScan
     */
    public void setIsScan(String value) {
        setAttributeInternal(ISSCAN, value);
    }

    /**
     * Gets the attribute value for IsJobCard, using the alias name IsJobCard.
     * @return the value of IsJobCard
     */
    public String getIsJobCard() {
        return (String) getAttributeInternal(ISJOBCARD);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsJobCard.
     * @param value value to set the IsJobCard
     */
    public void setIsJobCard(String value) {
        setAttributeInternal(ISJOBCARD, value);
    }

    /**
     * Gets the attribute value for Incentive, using the alias name Incentive.
     * @return the value of Incentive
     */
    public BigDecimal getIncentive() {
        return (BigDecimal) getAttributeInternal(INCENTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Incentive.
     * @param value value to set the Incentive
     */
    public void setIncentive(BigDecimal value) {
        setAttributeInternal(INCENTIVE, value);
    }

    /**
     * Gets the attribute value for IncentiveMsg, using the alias name IncentiveMsg.
     * @return the value of IncentiveMsg
     */
    public String getIncentiveMsg() {
        return (String) getAttributeInternal(INCENTIVEMSG);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncentiveMsg.
     * @param value value to set the IncentiveMsg
     */
    public void setIncentiveMsg(String value) {
        setAttributeInternal(INCENTIVEMSG, value);
    }

    /**
     * Gets the attribute value for SourceId, using the alias name SourceId.
     * @return the value of SourceId
     */
    public String getSourceId() {
        return (String) getAttributeInternal(SOURCEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceId.
     * @param value value to set the SourceId
     */
    public void setSourceId(String value) {
        setAttributeInternal(SOURCEID, value);
    }

    /**
     * Gets the attribute value for TotalImei, using the alias name TotalImei.
     * @return the value of TotalImei
     */
    public BigDecimal getTotalImei() {
        return (BigDecimal) getAttributeInternal(TOTALIMEI);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalImei.
     * @param value value to set the TotalImei
     */
    public void setTotalImei(BigDecimal value) {
        setAttributeInternal(TOTALIMEI, value);
    }

    /**
     * Gets the attribute value for ActiveDate, using the alias name ActiveDate.
     * @return the value of ActiveDate
     */
    public Date getActiveDate() {
        return (Date) getAttributeInternal(ACTIVEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ActiveDate.
     * @param value value to set the ActiveDate
     */
    public void setActiveDate(Date value) {
        setAttributeInternal(ACTIVEDATE, value);
    }

    /**
     * Gets the attribute value for SaleDate, using the alias name SaleDate.
     * @return the value of SaleDate
     */
    public Date getSaleDate() {
        return (Date) getAttributeInternal(SALEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleDate.
     * @param value value to set the SaleDate
     */
    public void setSaleDate(Date value) {
        setAttributeInternal(SALEDATE, value);
    }

    /**
     * Gets the attribute value for IncDebitAmount, using the alias name IncDebitAmount.
     * @return the value of IncDebitAmount
     */
    public BigDecimal getIncDebitAmount() {
        return (BigDecimal) getAttributeInternal(INCDEBITAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncDebitAmount.
     * @param value value to set the IncDebitAmount
     */
    public void setIncDebitAmount(BigDecimal value) {
        setAttributeInternal(INCDEBITAMOUNT, value);
    }

    /**
     * Gets the attribute value for SprDebitAmount, using the alias name SprDebitAmount.
     * @return the value of SprDebitAmount
     */
    public BigDecimal getSprDebitAmount() {
        return (BigDecimal) getAttributeInternal(SPRDEBITAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SprDebitAmount.
     * @param value value to set the SprDebitAmount
     */
    public void setSprDebitAmount(BigDecimal value) {
        setAttributeInternal(SPRDEBITAMOUNT, value);
    }

    /**
     * Gets the attribute value for SerialNo, using the alias name SerialNo.
     * @return the value of SerialNo
     */
    public String getSerialNo() {
        return (String) getAttributeInternal(SERIALNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SerialNo.
     * @param value value to set the SerialNo
     */
    public void setSerialNo(String value) {
        setAttributeInternal(SERIALNO, value);
    }

    /**
     * Gets the attribute value for IncentiveCancel, using the alias name IncentiveCancel.
     * @return the value of IncentiveCancel
     */
    public String getIncentiveCancel() {
        return (String) getAttributeInternal(INCENTIVECANCEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncentiveCancel.
     * @param value value to set the IncentiveCancel
     */
    public void setIncentiveCancel(String value) {
        setAttributeInternal(INCENTIVECANCEL, value);
    }

    /**
     * Gets the attribute value for IsCounterDead, using the alias name IsCounterDead.
     * @return the value of IsCounterDead
     */
    public String getIsCounterDead() {
        return (String) getAttributeInternal(ISCOUNTERDEAD);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsCounterDead.
     * @param value value to set the IsCounterDead
     */
    public void setIsCounterDead(String value) {
        setAttributeInternal(ISCOUNTERDEAD, value);
    }

    /**
     * Gets the attribute value for IncCanDoctype, using the alias name IncCanDoctype.
     * @return the value of IncCanDoctype
     */
    public String getIncCanDoctype() {
        return (String) getAttributeInternal(INCCANDOCTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncCanDoctype.
     * @param value value to set the IncCanDoctype
     */
    public void setIncCanDoctype(String value) {
        setAttributeInternal(INCCANDOCTYPE, value);
    }

    /**
     * Gets the attribute value for IncCanDocid, using the alias name IncCanDocid.
     * @return the value of IncCanDocid
     */
    public String getIncCanDocid() {
        return (String) getAttributeInternal(INCCANDOCID);
    }

    /**
     * Sets <code>value</code> as the attribute value for IncCanDocid.
     * @param value value to set the IncCanDocid
     */
    public void setIncCanDocid(String value) {
        setAttributeInternal(INCCANDOCID, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the value of StartDate
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for ExpDate, using the alias name ExpDate.
     * @return the value of ExpDate
     */
    public Date getExpDate() {
        return (Date) getAttributeInternal(EXPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpDate.
     * @param value value to set the ExpDate
     */
    public void setExpDate(Date value) {
        setAttributeInternal(EXPDATE, value);
    }

    /**
     * Gets the attribute value for Rowid, using the alias name Rowid.
     * @return the value of Rowid
     */
    public RowID getRowid() {
        return (RowID) getAttributeInternal(ROWID);
    }

    /**
     * Gets the attribute value for txtBrandid, using the alias name txtBrandid.
     * @return the value of txtBrandid
     */
    public String gettxtBrandid() {
        return (String) getAttributeInternal(TXTBRANDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtBrandid.
     * @param value value to set the txtBrandid
     */
    public void settxtBrandid(String value) {
        setAttributeInternal(TXTBRANDID, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getSrvJobcard() {
        return (RowIterator) getAttributeInternal(SRVJOBCARD);
    }

    /**
     * @return the associated entity InItemsImpl.
     */
    public InItemsImpl getInItems() {
        return (InItemsImpl) getAttributeInternal(INITEMS);
    }

    /**
     * Sets <code>value</code> as the associated entity InItemsImpl.
     */
    public void setInItems(InItemsImpl value) {
        setAttributeInternal(INITEMS, value);
    }

}

