package dgcom.model.qvo.srv.client;

import dgcom.model.qvo.srv.common.SrvLogDetSrvJobCardNoCIC_0082QVORow;

import oracle.jbo.client.remote.RowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 05 17:25:46 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvLogDetSrvJobCardNoCIC_0082QVORowClient extends RowImpl implements SrvLogDetSrvJobCardNoCIC_0082QVORow {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvLogDetSrvJobCardNoCIC_0082QVORowClient() {
    }

    public void doSelectDocument() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doSelectDocument", null, null);
        return;
    }
}

