package dgcom.model.qvo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 11 16:42:18 PKT 2017
// ---------------------------------------------------------------------
public interface PartExplorePartWiseQVO extends ViewObject {
    void executeEmptyRowSet();
}

