package dgcom.model.qvo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 06 10:15:23 PKT 2017
// ---------------------------------------------------------------------
public interface SrvLogDetSrvJobCardNoCIC_0082QVO extends ViewObject {
    void doSelectAllDocument();
}

