package dgcom.model.vo.srv.client;

import dgcom.model.vo.srv.common.SrvEpfsetsdetlVo;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 24 17:45:58 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvEpfsetsdetlVoClient extends ViewUsageImpl implements SrvEpfsetsdetlVo {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvEpfsetsdetlVoClient() {
    }

    public void doCreateNewExtractDetRow() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doCreateNewExtractDetRow", null, null);
        return;
    }
}

