package dgcom.model.vo.srv.client;

import dgcom.model.vo.srv.common.SrvInvoiceVO;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 11 18:16:23 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvInvoiceVOClient extends ViewUsageImpl implements SrvInvoiceVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvInvoiceVOClient() {
    }


    public void doSubmitServiceInvoice() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doSubmitServiceInvoice", null, null);
        return;
    }

    public void executeEmptyRowSet() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "executeEmptyRowSet", null, null);
        return;
    }
}

