package dgcom.model.vo.srv.client;

import dgcom.model.vo.srv.common.SrvJobhandovertolabVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 22 18:44:44 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobhandovertolabVOClient extends ViewUsageImpl implements SrvJobhandovertolabVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobhandovertolabVOClient() {
    }


    public void doCreateNewJobHORow() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doCreateNewJobHORow", null, null);
        return;
    }

    public void doSubmitJobHandOver() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doSubmitJobHandOver", null, null);
        return;
    }

    public void executeEmptyRowSet() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "executeEmptyRowSet", null, null);
        return;
    }
}

