package dgcom.model.vo.srv.client;

import dgcom.model.vo.srv.common.SrvJobtransferVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 20 17:32:43 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobtransferVOClient extends ViewUsageImpl implements SrvJobtransferVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobtransferVOClient() {
    }


    public void doCreateNewJobTransferRow() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doCreateNewJobTransferRow", null, null);
        return;
    }

    public void doSubmitJobTransfer() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doSubmitJobTransfer", null, null);
        return;
    }

    public void executeEmptyRowSet() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "executeEmptyRowSet", null, null);
        return;
    }
}

