package dgcom.model.vo.srv.client;

import dgcom.model.vo.srv.common.SrvJobsymptomVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 23 17:05:26 PKT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobsymptomVOClient extends ViewUsageImpl implements SrvJobsymptomVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobsymptomVOClient() {
    }

    public void doCreateNewJobSymRow() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doCreateNewJobSymRow", null, null);
        return;
    }
}

