package dgcom.model.vo.srv.client;

import dgcom.model.vo.srv.common.SrvJobassignVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 23 12:07:44 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvJobassignVOClient extends ViewUsageImpl implements SrvJobassignVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvJobassignVOClient() {
    }


    public void doCreateNewJobAssignRow() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doCreateNewJobAssignRow", null, null);
        return;
    }

    public void doSubmitJobAssign() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doSubmitJobAssign", null, null);
        return;
    }

    public void executeEmptyRowSet() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "executeEmptyRowSet", null, null);
        return;
    }
}

