package dgcom.model.vo.srv.client;

import dgcom.model.vo.srv.common.SrvStnreceivingVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 18 15:01:03 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvStnreceivingVOClient extends ViewUsageImpl implements SrvStnreceivingVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvStnreceivingVOClient() {
    }

    public void doSubmitStnReceiving() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doSubmitStnReceiving", null, null);
        return;
    }

    public void executeEmptyRowSet() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "executeEmptyRowSet", null, null);
        return;
    }
}

