package dgcom.model.vo.srv.client;

import dgcom.model.vo.srv.common.SrvSetdeliveryVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 14 09:39:53 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SrvSetdeliveryVOClient extends ViewUsageImpl implements SrvSetdeliveryVO {
    /**
     * This is the default constructor (do not remove).
     */
    public SrvSetdeliveryVOClient() {
    }

    public void doSubmitSetDelivery() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "doSubmitSetDelivery", null, null);
        return;
    }

    public void executeEmptyRowSet() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this, "executeEmptyRowSet", null, null);
        return;
    }
}

