package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 10 10:41:49 PKT 2016
// ---------------------------------------------------------------------
public interface PuSupplierInvoicesVO extends ViewObject {
    void doSubmitSupplierInvoice();

    void executeEmptyRowSet();
}

