package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 16:13:33 PKT 2017
// ---------------------------------------------------------------------
public interface SrvBomVO extends ViewObject {
    void executeEmptyRowSet();

    void doCreateNewBOMRow();
}

