package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 24 18:16:08 PKT 2017
// ---------------------------------------------------------------------
public interface SrvDealersVO extends ViewObject {
    void executeEmptyRowSet();
}

