package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 26 23:44:12 PKT 2016
// ---------------------------------------------------------------------
public interface SrvDiscountNoteVO extends ViewObject {
    void doSubmitSrvDiscountNote();
}

