package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jul 25 11:24:54 PKT 2016
// ---------------------------------------------------------------------
public interface SrvEpfsetsVO extends ViewObject {
    void doSubmitDismental();

    void doCreateNewEetractPartRow();

    void executeEmptyRowSet();
}

