package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 24 17:38:30 PKT 2017
// ---------------------------------------------------------------------
public interface SrvEstdetlVO extends ViewObject {
    void doCreateNewExtractPartDetRow();
}

