package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 19 12:08:18 PKT 2016
// ---------------------------------------------------------------------
public interface SrvIssuereturnVO extends ViewObject {
    void doSubmitIssueReturn();

    void executeEmptyRowSet();
}

