package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 27 13:06:25 PKT 2016
// ---------------------------------------------------------------------
public interface SrvIssuanceVO extends ViewObject {
    void doSubmitIssuance();

    void executeEmptyRowSet();

    void doCreateNewIssuanceRow();
}

