package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 24 13:15:31 PKT 2017
// ---------------------------------------------------------------------
public interface SrvJobactionVO extends ViewObject {
    void doCreateNewJobActionRow();
}

