package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 29 10:17:22 PKT 2016
// ---------------------------------------------------------------------
public interface SrvJobcomplainVO extends ViewObject {
    void executeEmptyRowSet();
}

