package dgcom.model.vo.srv.common;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 20 17:22:38 PKT 2016
// ---------------------------------------------------------------------
public interface SrvJobcardVO extends ViewObject {
    void doSubmitJobCard();

    void executeEmptyRowSet();

    void doCreateNewJobCardRow();
}

