package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 05 10:30:41 PKT 2016
// ---------------------------------------------------------------------
public interface SrvJobreturnVO extends ViewObject {
    void doSubmitJobReturn();

    void executeEmptyRowSet();

    void doCreateNewJobReturnRow();
}

