package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 29 14:02:14 PKT 2016
// ---------------------------------------------------------------------
public interface SrvJobsolutionVO extends ViewObject {
    void doSubmitJobSolutions();

    void executeEmptyRowSet();

    void doCreateNewJobSolRow();
}

