package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Feb 23 17:05:25 PKT 2017
// ---------------------------------------------------------------------
public interface SrvJobsymptomVO extends ViewObject {
    void doCreateNewJobSymRow();
}

