package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 19 22:52:57 PKT 2016
// ---------------------------------------------------------------------
public interface SrvLogisticVO extends ViewObject {
    void doSubmitJobLogistic();

    void doSubmitPendingJobLogistic();

    void executeEmptyRowSet();

    void doCreateNewLogisticRow();
}

