package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 22 17:52:43 PKT 2016
// ---------------------------------------------------------------------
public interface SrvPartsalesVO extends ViewObject {
    void doSubmitPartSale();

    void doCreateNewPartSaleRow();

    void executeEmptyRowSet();
}

