package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 25 11:35:35 PKT 2017
// ---------------------------------------------------------------------
public interface SrvStnpartsVO extends ViewObject {
    void doCreateNewStnDetRow();
}

