package dgcom.model.vo.srv.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Feb 25 12:57:51 PKT 2017
// ---------------------------------------------------------------------
public interface SrvSadjustdetlVO extends ViewObject {
    void doCreateNewStockAdjDetRow();
}

